<?php

/**
 * AdminOnSteroids
 * Various ProcessWire admin tweaks to boost productivity
 *
 * @author Roland Toth (tpr)
 *
 * ProcessWire 3.x
 * Copyright (C) 2011 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */
class AdminOnSteroids extends \ProcessWire\WireData implements \ProcessWire\Module, \ProcessWire\ConfigurableModule
{
    static $configData;
    public $adminTheme;
    protected $editedPage;
    protected $PageListThumbs_items;
    protected $PageListIcons;
    protected $settingsFile;
    protected $htmlClasses;
    protected $isLocaleSet;
    protected $allRoles;
    protected $enabledSubmodules;

    public static function getModuleInfo()
    {
        return array(
            'title'     => 'AdminOnSteroids',
            'class'     => 'AdminOnSteroids',
            'version'   => '170',
            'summary'   => \ProcessWire\__('Various ProcessWire admin tweaks to boost productivity'),
            'author'    => 'Roland Toth',
            'autoload'  => 'template=admin',
            'href'      => 'https://processwire.com/talk/topic/13389-adminonsteroids/',
            'icon'      => 'medkit',
            'requires'  => 'ProcessWire>=2.8.0, PHP>=5.3.8',
            'singular'  => true,
            'permanent' => false
        );
    }

    public function __construct()
    {
        $this->settingsFile = \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids' . "/settings.php";
    }

    /**
     * Default configuration for module
     *
     */
    static public function getDefaultData()
    {
        return array(
            'enabledSubmodules'                 => array(
//                'AdminTweaks',
//                'AsmTweaks',
//                'CKEaddons',
//                'DeselectRadios',
//                'FieldAndTemplateEditLinks',
//                'FileFieldTweaks',
//                'FocusInputOnLangTabSwitch',
//                'Hotkeys',
//                'InputfieldURLChecker',
//                'ListerTweaks',
//                'LongClickDuration',
//                'Misc',
//                'ModuleTweaks',
//                'NavItems',
//                'PageListIcons',
//                'PageListThumbs',
//                'PageListTweaks',
//                'PagePreviewBtn',
//                'RenoTweaks',
//                'Tooltips'
            ),
            'enabled'                           => 1,
            'restore'                           => '',
            'AddNewChildFirst_enabledTemplates' => array(),
            'AdminStyle'                        => '',
            'AdminScript'                       => '',
            'AdminTweaks'                       => array(
//                'headSticky',
//                'leftTopnav',
//                'wide'
            ),
            'AsmTweaks'                         => array(
//                'asmCollapse',
//                'fieldMiddleEdit',
//                'editFieldWidth',
//                'asmLeftX'
            ),
            'CKEStyle'                          => '',
            'CKEScript'                         => '',
            'CKEtemplates'                      => '',
            'CKEaddons_plugins'                 => array(),
            'CKEaddons_skin'                    => 'default',
            'CKEaddons_enabledFields'           => '',
            'DeselectRadios'                    => array(
                'adminOnly'
            ),
            'FieldAndTemplateEditLinks'         => 'pw-blank',
            'FieldOverrides'                    => '',
            'FieldOverridesFile'                => '',
            'BrandingLogo'                      => '',
            'FileFieldTweaks'                   => array(
//                'filterbox',
//                'downloadAssetButton',
//                'moveAssetButtons',
//                'noFilenameTruncate',
//                'imgSelectTitle'
            ),
            'FocusInputOnLangTabSwitch'         => array(
                'focus'
            ),
            'FocusInputOnLangTabSwitchCKE'      => array(
                'focus'
            ),
            'Hotkeys'                           => array(
//                'save',
//                'focusSearch',
//                'breadcrumbTweaks',
//                'addPageTreeTrigger',
//                'filterboxHotkey',
//                'removeNoticeHotkey'
            ),
            'IUC_mode'                          => array(
                'button'
            ),
            'IUC_buttonPosition'                => 'button-left',
            'IUC_target'                        => 'pw-blank',
            'IUC_forceHttp'                     => '',
            'IUC_enabledTemplates'              => array(),
            'IUC_enabledFields'                 => array(),
            'ListerTweaks'                      => '',
            'ListerTweaks_find'                 => array(
//                'title',
//                'template',
//                'parent',
//                'modified',
//                'modified_users_id'
            ),
            'ListerTweaks_users'                => array(
//                'name',
//                'email',
//                'roles'
            ),
            'ListerTweaks_options'              => array(
//                'listerHoverBtn',
//                'hideTemplateEditAction'
            ),
            'LongClickDuration'                 => 600,
            'Misc'                              => array(
//                'adminColumns',
//                'autosizeTextareas',
//                'addOrRemoveFieldsTweaks',
//                'homeOpenNewTab',
//                'dataTableFilter',
//                'transFilter',
//                'langTabHotkeySwitcher',
//                'centerLogin',
//                'hoverDropdown',
//                'titleCaseToggle',
//                'tabIndex',
//                'emptyTrashTop',
//                'iconsFilter',
//                'stickyCKE'
//                'noAnim'
            ),
            'ModuleTweaks'                      => array(
//                'loadCollapsedModuleInfos',
//                'flatModules',
//                'moduleCompact',
//                'moduleFilter',
//                'moduleModal'
            ),
            'NavItems'                          => 1,
            'NavItems_pages'                    => array(),
            'NavItems_pages_submenu'            => '',
            'NavItems_custom'                   => array(),
            'PagePreviewBtn'                    => 'pw-blank',
            'PageListThumbs'                    => array(),
            'PageListThumbs_style'              => 'circle',
            'PageListThumbs_items'              => '',
            'PageListIcons'                     => '',
            'PageListThumbs_options'            => array(//                'alignright'
            ),
            'PageListTweaks'                    => array(
//                'pListIDs',
//                'highlightRows',
//                'pListMiddleClick',
//                'pListCounters',
                //'pListTrash',
//                'pListMarkup',
//                'pListUnselect'
            ),
            'RenoTweaks'                        => array(
//                'sbSingleClickHeads',
//                'headSticky',
////                'headStickyCompact',
//                'miniScrollSb',
////                'miniScrollMain',
//                'sbSticky',
////                'sbAutoHide',
//                'sbItemsVisible',
////                'sbQuickLinksHide',
////                'sbItemsInline',
//                'headBtnToTitle',
//                'pListFullRowHover',
//                'openSearch',
//                'pListCompact',
//                'noticeLeftX',
//                'hoverTopSubmenus'
            ),
            'RestrictTreeDropdown'              => '',
            'Tooltips'                          => array(
//                'tooltipDesc',
//                'tooltipNotes'
//                'tooltipOverlay'
            ),
            'UikitTweaks'                       => array(//                'headSticky',
            )
        );
    }

    public function __toString()
    {
        return __CLASS__;
    }

    protected function _installColumnBreakField()
    {

        // install AdminColumns field
        // use skipLabel and collapsed to avoid visiblity if AOS is uninstalled (no need to remove from templates)
        if ($this->fields->get('aos_column_break')) {
            return;
        }

        $field = new \ProcessWire\Field();
        $field->type = $this->modules->get("FieldtypeText");
        $field->name = 'aos_column_break';
        $field->label = '';
        $field->skipLabel = true;
        $field->collapsed = \ProcessWire\Inputfield::collapsedYesLocked;
        $field->tags = '-aos';
//        $field->columnWidth = 67;
        $field->save();

        $this->message(\ProcessWire\__('Added "aos_column_break" field for AdminColumns submodule.', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
    }


    public function ___install()
    {
        @$previousSettings = file_get_contents($this->settingsFile);

        if ($previousSettings) {
            $previousSettings = json_decode($previousSettings, true);

            // check if "restore" is enabled
            if (isset($previousSettings['restore']) && $previousSettings['restore'] == 1) {
//                $settings = $previousSettings;
                $this->wire('modules')->saveModuleConfigData($this, $previousSettings);
            }
        }

        $this->_installColumnBreakField();
    }


    public function ___uninstall()
    {
        // save current config to settings.php
        $settings = array_filter($this->modules->getModuleConfigData($this));
        @file_put_contents($this->settingsFile, json_encode($settings));
    }


    public function addClasses(\ProcessWire\HookEvent $event)
    {
        $allowedHtmlClasses = array(
            'adminColumns',
            'AdminThemeDefault',
            'AdminThemeUikit',
            'BrandingLogo',
            'headCompact',
            'hoverTopSubmenus',
            'asmCollapse',
            'asmLeftX',
            'centerLogin',
            'downloadAssetButton',
            'editFieldWidth',
            'emptyTrashTop',
            'filterbox',
            'flatModules',
            'headBtnToTitle',
            'headSticky',
            'headStickyCompact',
            'hideAddNewDropdown',
            'hoverDropdown',
            'leftTopnav',
            'ListerTweaks',
            'listerHoverBtn',
            'moduleCompact',
            'moduleModal',
            'moveAssetButtons',
            'noAnim',
            'noFilenameTruncate',
            'noticeLeftX',
            'openSearch',
            'pListActiveBold',
            'pListCompact',
            'pListFullRowHover',
            'pListIconOnly',
            'pListShowActions',
            'pListCounters',
            'PageListThumbs',
            'highlightRows',
            'sbAutoHide',
            'sbItemsInline',
            'sbItemsVisible',
            'sbQuickLinksHide',
            'sbSticky',
            'stickyCKE',
            'themeConfigLinks',
            'tooltipDesc',
            'tooltipNotes',
            'tooltipOverlay',
            'wide'
        );

        // eg. checkboxes inside fieldsets
        // need to add its PARENT submodule name to the allowed html classes
        $itemsToTreatAsSubmodule = array('ListerTweaks_options');

        foreach (array_merge($this->enabledSubmodules, $itemsToTreatAsSubmodule) as $submodule) {

            $this->addDOMClass($submodule);

            if (isset(self::$configData[$submodule]) && is_array(self::$configData[$submodule])) {
                foreach (self::$configData[$submodule] as $item) {
                    $this->addDOMClass(array($submodule, $item));
                }
            }
        }

        $html = $event->return;

        // add empty class to html (default theme has no html class but check always)
        if (!preg_match("/<html(.+)class=(.+)>/i", $html)) {
            $html = str_replace('<html', '<html class=""', $html);
        }

        if ($this->adminTheme === 'AdminThemeDefault') {
            $this->htmlClasses[] = 'AdminThemeDefault';
        }

        if ($this->adminTheme === 'AdminThemeUikit') {
            $this->htmlClasses[] = 'AdminThemeUikit';
        }

        if ($this->BrandingLogo) {
            $this->htmlClasses[] = 'BrandingLogo';
        }

        if (!$this->wire('user')->isSuperUser()) {
            if (($key = array_search('themeConfigLinks', $this->htmlClasses)) !== false) {
                unset($this->htmlClasses[$key]);
            }
        }

        $htmlClasses = implode(' ', array_intersect($allowedHtmlClasses, $this->htmlClasses));

        $event->return = preg_replace("/<html(.+)class=('|\")(.*?)('|\")/i",
            "<html$1class=$2aos $3 " . $htmlClasses . "$4", $html);
    }


    public function addDOMClass($class)
    {
        if (is_array($class)) {

            // do not mess similar features enabled for another admin theme
            if (
                ($class[0] === 'AdminTweaks' && $this->adminTheme !== 'AdminThemeDefault') ||
                ($class[0] === 'RenoTweaks' && $this->adminTheme !== 'AdminThemeReno') ||
                ($class[0] === 'UikitTweaks' && $this->adminTheme !== 'AdminThemeUikit')
            ) {
                return false;
            }

            if (is_array($class[1])) {
                return $this->addDOMClass($class[0]);
            }

            if (in_array($class[1], self::$configData[$class[0]])) {
                $class = $class[1];
            } else {
                return '';
            }
        }

        $this->htmlClasses[] = $class;
    }


    public function ___modifyConfigData($data)
    {
        return $data;
    }


    public function init()
    {

        // populate self::$configData
        $configData = $this->modules->getModuleConfigData($this);
        self::$configData = $configData;

        if ($this->user->isSuperUser()) {

            if ($this->input->toggle == 1) {
                $configData['enabled'] = ($this->enabled == 1) ? 0 : 1;
                $this->modules->saveModuleConfigData($this, $configData);

                $this->session->redirect($_SERVER['HTTP_REFERER']);

                $this->halt();
            }

            $this->addHookAfter('AdminTheme::getExtraMarkup', $this, 'addAOSToggleLink');
        }

        $this->allRoles = array();

        foreach ($this->roles as $role) {
            if ($role->name == 'guest') {
                continue;
            }
            $this->allRoles[$role->name] = $role->name;
        }

        if (!$this->enabled) {
            return;
        }

        $enabledSubmodules = self::$configData['enabledSubmodules'];

        // remove submodules where user's role is not allowed

        if (!$this->user->isSuperUser()) {
//        $userRoles = $this->user->roles->explode('name');
            $userRoles = $this->user->roles->name(',');

            // remove 'guest' role
            $userRoles = str_replace(array('guest', ',,'), array('', ','), $userRoles);
            $userRoles = trim($userRoles, ',');
            $userRoles = explode(',', $userRoles);


            foreach ($enabledSubmodules as $submodule) {

                $submoduleRoleField = $submodule . 'Roles';

                // continue if no roles have been set in module config (empty means allow all)
                if (empty($this->$submoduleRoleField)) {
                    continue;
                }

//            remove from array (by value) if there isn't a matching role
                if (count(array_intersect($this->$submoduleRoleField, $userRoles)) == 0) {
                    if (($key = array_search($submodule, $enabledSubmodules)) !== false) {
                        unset($enabledSubmodules[$key]);
                    }
                }
            }
        }

        $this->enabledSubmodules = $enabledSubmodules;

        // adminLangSwitcher (Misc)
        $subModule = 'Misc';

        // add to init() to change early
        if (in_array($subModule, $enabledSubmodules)) {
            if (in_array('adminLangSwitcher', $configData[$subModule])) {
                if (isset($_COOKIE["aos_lang_id"])) {
                    $lang_id = $_COOKIE["aos_lang_id"];
                    $this->user->language = $lang_id;
                }
            }
        }
    }


    public function ready()
    {
        $root = $this->config->urls->siteModules . __CLASS__;
        $styles = $this->config->styles;
        $scripts = $this->config->scripts;
        $moduleInfo = $this->getModuleInfo();
        $timestamp = $moduleInfo['version'] . '_' . date('YmdH');

        if ($this->input->get['name'] == 'AdminOnSteroids') {
            $scripts->add($root . '/scripts/aos_config.min.js?ts=' . $timestamp);
            $styles->prepend($root . '/styles/aos_config.min.css?ts=' . $timestamp);
            $styles->prepend($root . '/styles/aos.min.css?ts=' . $timestamp);   // for the real-time aos settings preview

            if (!$this->wire('modules')->isInstalled('InputfieldAceExtended')) {
                $styles->add($root . '/CKE/plugins/codemirror/css/codemirror.min.css');
                $styles->add($root . '/CKE/plugins/codemirror/theme/twilight.css');
                $scripts->add($root . '/CKE/plugins/codemirror/js/codemirror.min.js');
                $scripts->add($root . '/CKE/plugins/codemirror/js/properties.js');
            }
        }

        if (!$this->enabled) {
            return false;
        }

        // set $this->editedPage
        // excluded repeater pages, minor refactoring
        $this->editedPage = false;
        $editedPageId = $this->sanitizer->int($this->config->input->get->id);
        $editedPage = $this->pages->get($editedPageId);

        if ($editedPage->id && !($editedPage instanceof \ProcessWire\RepeaterPage)) {
            $this->editedPage = $editedPage;
        }

        self::$configData = $this->modifyConfigData(
            $this->modules->getModuleConfigData($this),
            $this->editedPage
        );

        $styles->prepend($root . '/styles/aos.min.css?ts=' . $timestamp);

        // login page doesn't need some stuff
        if ($this->page->id != 23) {
            $scripts->add($root . '/scripts/aos.min.js?ts=' . $timestamp);

            // always load modal js
            $this->modules->get('JqueryUI')->use('modal');
        }

        $configData = self::$configData;
        $defaultData = self::getDefaultData();

        $enabledSubmodules = $this->enabledSubmodules;

        $this->htmlClasses = array();
        $jsFiles = array();
        $cssFiles = array();

        // if there's only the default admin theme, $user->admin_theme is not available
        $this->adminTheme = $this->user->admin_theme ? $this->user->admin_theme : $this->config->defaultAdminTheme;

        $this->PageListThumbs_items = array();
        $this->PageListIcons = array();

        $this->addHookAfter('Page::render', $this, 'addClasses');

        // add extra clases to admin body (by Robin S)
        $this->addHookAfter('AdminTheme::getExtraMarkup', $this, 'addAdminClasses');

        //NavItems
        $subModule = 'NavItems';

        if (in_array($subModule, $enabledSubmodules)) {
            if ($this->wire('page')->id !== 23) {
                $this->addHookAfter('Page::render', $this, 'addNavItems');
            }
        }

        if ($this->BrandingLogo) {
            $this->addHookAfter('Page::render', function (\ProcessWire\HookEvent $event) {
                $markup = $event->return;

                if ($this->adminTheme === 'AdminThemeUikit') {
                    $markup = str_replace($this->wire('config')->urls->adminTemplates . 'uikit/custom/images/pw-mark.png', $this->BrandingLogo, $markup);
                } elseif ($this->adminTheme === 'AdminThemeDefault') {
                    $markup = str_replace($this->wire('config')->urls->adminTemplates . 'styles/images/logo.png', $this->BrandingLogo, $markup);
                } elseif ($this->adminTheme === 'AdminThemeReno') {
                    $markup = str_replace('<a id="logo"', '<a id="logo" style="background-image: url(\'' . $this->BrandingLogo . '\');"', $markup);
                }

                $event->return = $markup;
            });
        }

        //FieldAndTemplateEditLinks
        $subModule = 'FieldAndTemplateEditLinks';
        if (in_array($subModule, $enabledSubmodules)) {

            if ($this->user->isSuperUser()) {

                // add template edit link (page action) to pagelist
                $this->addHookAfter("ProcessPageListActions::getActions", $this, 'addTemplateEditLinkPageList');

                if ($this->editedPage) {

                    // add edit field link only if the edited page is not a special page (eg. admin)
                    if ($this->process == 'ProcessPageView' && $this->editedPage->template && $this->editedPage->template->flags === 0) {
                        $this->addHookAfter('Page::render', $this, 'addTemplateEditLink');
                        $this->addHookAfter('Inputfield::render', $this, 'addFieldEditLinks');
                        $this->addHookAfter('Inputfield::renderValue', $this, 'addFieldEditLinks');
                    }
                }
            } else {
                // remove the submodule entirely if not superuser
                if (($key = array_search($subModule, $enabledSubmodules)) !== false) {
                    unset($enabledSubmodules[$key]);
                }
            }
        }

//        $this->addHookBefore('ProcessPageList::execute', function(\ProcessWire\HookEvent $event) {
//            // overwrite GET lang parameter
//            $this->input->get['lang'] = 1020;
//        });


        //DeselectRadios
//        $subModule = 'DeselectRadios';
//        if (in_array($subModule, $enabledSubmodules)) {
//            $jsFiles[] = $root . '/' . $subModule . '/' . $subModule . '.js';
//        }


        //InputfieldURLChecker
        $subModule = 'InputfieldURLChecker';
        if (in_array($subModule, $enabledSubmodules)) {

//            $jsFiles[] = $root . '/' . $subModule . '/' . $subModule . '.js';
//            $cssFiles[] = $root . '/' . $subModule . '/' . $subModule . '.css';

            $this->addHookAfter('InputfieldURL::renderValue', $this, 'addIUCLink');
            $this->addHookAfter('InputfieldURL::render', $this, 'addIUCLink');
            $this->addHookAfter('InputfieldPageAutocomplete::render', $this, 'addIUCLink');
        }

        //AsmTweaks
//        $subModule = 'AsmTweaks';
//        if (in_array($subModule, $enabledSubmodules)) {
//            $jsFiles[] = $root . '/' . $subModule . '/' . $subModule . '.js';
//        }

        //PageListTweaks
        $subModule = 'PageListTweaks';
        if (in_array($subModule, $enabledSubmodules)) {

            // always add hook to remove markup if tweak is disabled
            $this->addHookAfter("ProcessPageListRender::getPageLabel", $this, 'addPageListMarkup');

            if ($this->languages) {
                $this->addHookBefore("ProcessPageListRender::getPageLabel", $this, 'pageListMarkupGetLangValue');
            }

            // pListUnselect
            if (in_array('pListUnselect', $configData[$subModule])) {
                $this->addHookAfter('InputfieldPageListSelect::render', $this, 'addPageListUnselectButtons');
            }

            if ($this->wire('user')->isSuperUser()) {

                if (in_array('pListIDs', $configData[$subModule])) {
                    $this->addHookAfter("ProcessPageListRender::getPageLabel", $this, 'addPageListIDs');
                }


                // add delete button to pagelist items (bypass trash)
                if (in_array('deleteBtn', $configData[$subModule])) {
                    $this->addHookAfter("ProcessPageListActions::getExtraActions", $this, 'addDeleteButton');
                    $this->addHookAfter('ProcessPageListActions::processAction', $this, 'addDeleteButtonAction');
                }
            }

            if (in_array('refreshBtn', $configData[$subModule])) {
                $this->addHookAfter("ProcessPageListActions::getExtraActions", function (\ProcessWire\HookEvent $event) {

                    $page = $event->arguments('page');

                    $actions = array();
                    $adminUrl = $this->wire('config')->urls->admin . 'page/';

                    $actions['refresh'] = array(
                        'cn'   => 'Refresh',
                        'name' => 'Refresh',
                        'url'  => $adminUrl . '?action=refresh&id=' . $page->id,
                        'ajax' => true
                    );

                    $event->return += $actions;
                });

                $this->addHookAfter('ProcessPageListActions::processAction', function (\ProcessWire\HookEvent $event) {

                    $page = $event->arguments(0);
                    $action = $event->arguments(1);

                    if ($action == 'refresh') {

                        $remove = false;
                        $refreshChildren = $page->id;

                        // remove item if there's no ID or it's in the Trash
                        if (!$page->id || ($page->parent && $page->parent->id == 7)) {
                            $remove = true;
                            $refreshChildren = 0;
                        }

                        $event->return = array(
                            'action'          => $action,
                            'success'         => true,
                            'page'            => $page->id,
                            'updateItem'      => $page->id,
                            'message'         => 'Page refreshed.',
                            'remove'          => $remove,
                            'refreshChildren' => $refreshChildren
                        );
                    }
                });
            }

            if (in_array('pListTrash', $configData[$subModule])) {
                if (!$this->wire('user')->isSuperUser()) {
                    $this->addHookAfter('ProcessPageListActions::getExtraActions', $this, 'addTrashButton');
                }
            }

//            if (in_array('pListLangs', $configData[$subModule])) {
//                if ($this->wire('languages') && $this->wire('pages')->find('template=language, check_access=0')->count() > 1) {
//                    $this->addHookAfter("ProcessPageListRender::getPageLabel", $this, 'addLanguageIndicators');
//                }
//            }
        }


        // ListerTweaks

        $subModule = 'ListerTweaks';
        // default columns: only add hook if there's no bookmark requested
        if (in_array($subModule, $enabledSubmodules) && (!isset($_SERVER['HTTP_REFERER']) || strpos($_SERVER['HTTP_REFERER'], '?bookmark=') === false) && (!empty(self::$configData['ListerTweaks_find']) || !empty(self::$configData['ListerTweaks_users']))) {
            $this->addHookBefore('ProcessPageLister::execute', function ($event) {

                // do not mess with ListerPro
                if ($this->wire('page')->process == 'ProcessPageListerPro') {
                    return false;
                }

                $lister = $event->object;
                $columns = array();
                $pagePath = $this->page->path;
                $defaultData = self::getDefaultData();

                // 1007: Find
                // 29: Users
                if (strpos($pagePath, '/page/lister/') !== false) {
                    $listerType = 'ListerTweaks_find';
                } elseif (strpos($pagePath, '/access/users/') !== false) {
                    $listerType = 'ListerTweaks_users';
                }

                if (!isset($listerType)) {
                    return false;
                }

                $defaultFields = $defaultData[$listerType];

                if (!empty(self::$configData[$listerType])) {
                    foreach (self::$configData[$listerType] as $ff) {
                        if ($ff == '[DEFAULTS]') {
                            $columns += $defaultFields;
                            continue;
                        }
                        $columns[] = $ff;
                    }
                }

                if (!empty($columns)) {
//                    $lister->sessionSet('columns', false);
//                } else {
                    $lister->sessionSet('columns', $columns);
                }

            });
        }


        //RenoTweaks
        $subModule = 'RenoTweaks';
        if ($this->adminTheme === 'AdminThemeReno' && in_array($subModule, $enabledSubmodules)) {
            if (in_array('headSticky', $configData[$subModule])) {
                if (in_array('miniScrollSb', $configData[$subModule]) || in_array('miniScrollMain',
                        $configData[$subModule])
                ) {
                    $jsFiles[] = $root . '/scripts/vendor/perfect-scrollbar/js/perfect-scrollbar.min.js';
                }
            }
        }


        //RestrictTreeDropdown
        $subModule = 'RestrictTreeDropdown';

        if (in_array($subModule, $enabledSubmodules)) {
            $user = $this->wire('user');
            $selected_roles = $this->RestrictTreeDropdown;

            if (!empty($selected_roles)) {

                $prevent_dropdown = false;
                if (in_array('all-roles', $selected_roles)) {
                    $prevent_dropdown = true;
                } elseif (!$this->wire('user')->isSuperUser() && in_array('nonsuperuser', $selected_roles)) {
                    $prevent_dropdown = true;
                } elseif (count(array_intersect($selected_roles, $user->roles->explode('name')))) {
                    $prevent_dropdown = true;
                }

//                if ($prevent_dropdown) {
                $configData['RestrictTreeDropdown'] = $prevent_dropdown;
//                }
            }
        }


        //AddNewChildFirst

        $subModule = 'AddNewChildFirst';

        if (in_array($subModule, $enabledSubmodules)) {

            $this->addHookAfter("Pages::added", function (\ProcessWire\HookEvent $event) {
                $page = $event->arguments[0];
                $selected_templates = $this->AddNewChildFirst_enabledTemplates;

                if (is_array($selected_templates) && array_intersect(array('__all__', $page->template->name),
                        $selected_templates)
                ) {
                    $this->wire('pages')->sort($page, 0);
                }
            });
        }

        // FieldOverrides
        $subModule = 'FieldOverrides';
        if (in_array($subModule, $enabledSubmodules)) {

            if ($this->wire('process') !== 'ProcessPageEdit') {   // enable only on page edit screen

                $fieldoverrides_admin_contents = array();
                $fieldoverrides_file_contents = array();

                // check wether there is file-based settings
                if ($this->FieldOverridesFile && file_exists($this->FieldOverridesFile)) {

                    // make array if file-based settings is an ini file
                    $filename_array = explode(".", $this->FieldOverridesFile);
                    $extension = end($filename_array);

                    if ($extension === 'ini') {
                        $file_contents = file_get_contents($this->FieldOverridesFile);
                        $fieldoverrides_file_contents = parse_ini_string($file_contents, true);
                    } else {
                        if ($extension === 'php') {
 include_once(\ProcessWire\wire('files')->compile($this->FieldOverridesFile,array('includes'=>true,'namespace'=>true,'modules'=>false,'skipIfNamespace'=>false)));
                            // $fieldoverrides should be the name of the array in the included file
                            if (isset($fieldoverrides) && is_array($fieldoverrides)) {
                                $fieldoverrides_file_contents = $fieldoverrides;
                            }
                        }
                    }
                }

                // make array from admin-based settings (only ini format)
                if (!empty($this->FieldOverrides)) {
                    $fieldoverrides_admin_contents = parse_ini_string($this->FieldOverrides, true);
                }

                // merge the two
                $fieldoverrides = array_merge($fieldoverrides_admin_contents, $fieldoverrides_file_contents);

                if (!empty($fieldoverrides)) {
                    $this->FieldOverrides = $fieldoverrides;
                    $this->addHookBefore('Field::getInputfield', $this, 'setFieldOverrides');
                }
            }
        }

        //FocusInputOnLangTabSwitch
//        $subModule = 'FocusInputOnLangTabSwitch';
//        if (in_array($subModule, $enabledSubmodules)) {
//            $jsFiles[] = $root . '/' . $subModule . '/' . $subModule . '.js';
//        }

        //Hotkeys
        $subModule = 'Hotkeys';
        if (in_array($subModule, $enabledSubmodules)) {

            // add breadcrumb tweaks
            if (in_array('breadcrumbTweaks', $configData[$subModule])) {

                $editedPage = $this->editedPage;

                if ($editedPage && $editedPage->id) {
                    $homepage = $this->wire('pages')->get(1);
                    $breadcrumbUrls = array();

                    foreach ($editedPage->parents() as $p) {
//						$p->of(false);	// fix breadcrumb html-encoded value issue (fixed in PW 3.05x)
                        $breadcrumbUrls[] = array(
                            'url'     => $p->viewable() ? $p->httpUrl : null,
                            'editUrl' => $p->editable() ? rtrim($homepage->httpUrl, '/') . $p->editUrl : null
                        );
                    }

                    $this->wire('config')->js("AOS_breadcrumbs", $breadcrumbUrls);    // add to js config (head)
                }
            }
            // see main js file
//            $jsFiles[] = $root . '/' . $subModule . '/' . $subModule . '.js';
        }


        //LongClickDuration
        $subModule = 'LongClickDuration';
        if (in_array($subModule, $enabledSubmodules)) {

            $LongClickDuration = (int)$configData['LongClickDuration'];

            //do not allow lower value than default 600
            $LongClickDuration = ($LongClickDuration < $defaultData['LongClickDuration']) ? $defaultData['LongClickDuration'] : $LongClickDuration;

            $configSettings['LongClickDuration'] = $LongClickDuration;
        } else {
            // need to set default value explicitly
            $configSettings['LongClickDuration'] = $defaultData['LongClickDuration'];
        }


        // CKEaddons
//        $subModule = 'CKEaddons';
//
//        if (in_array($subModule, $enabledSubmodules)) {
//
//        }


        // Misc
        $subModule = 'Misc';
        if (in_array($subModule, $enabledSubmodules)) {

            // adminColumns
            if (in_array('adminColumns', $configData[$subModule])) {
                // make sure field is available
                $this->_installColumnBreakField();
                $this->addHookAfter('ProcessPageEdit::buildFormContent', $this, 'setupAdminColumns');
                $jsFiles[] = $root . '/scripts/vendor/split.js/split.min.js';
            }

            // adminLangSwitcher
            if (in_array('adminLangSwitcher', $configData[$subModule])) {
                $this->addHookAfter('AdminTheme::getExtraMarkup', $this, 'addAdminLangSwitcher');
            }

            // uncheckAddnewActive
            if (in_array('uncheckAddnewActive', $configData[$subModule])) {
                $this->addHookAfter('InputfieldPageName::render', $this, 'uncheckAddnewActive');
            }

            // addTranslatorLinks
            if (in_array('addTranslatorLinks', $configData[$subModule])) {
                if ($this->page->process == "ProcessLanguageTranslator" && $this->wire('languages')->count() > 1) {
                    $this->addHookAfter('ProcessLanguageTranslator::executeEdit', $this, 'addTranslatorLinks');
                }
            }


            // showSystemTemplates
            if (in_array('showSystemTemplates', $configData[$subModule])) {

                if ($this->wire('user')->isSuperUser()) {
                    $this->addHookBefore('ProcessField::buildEditFormInfo', function () {
                        // Show system templates in templates list of Edit Field
                        $this->wire('config')->advanced = true;
                    });

                    $this->addHookBefore('ProcessTemplate::executeNavJSON', function () {
                        // Show system templates in admin menu
                        $this->wire('config')->advanced = true;
                    });

                    if (!$this->wire('input')->get('id') && $this->wire('page')->process == 'ProcessTemplate') {
//                $this->addHookAfter('Session::loginSuccess(roles=superuser)', null, function () {
                        // Show system templates in templates list unless explicitly hidden
                        $this->wire('session')->set('ProcessTemplateFilterSystem', 1);
                    }
//                });
                }
            }


            // autosizeTextareas
            if (in_array('autosizeTextareas', $configData[$subModule])) {
                $jsFiles[] = $root . '/scripts/vendor/autosize/autosize.min.js';
            }


            // prevNextLinks
            if (in_array('prevNextLinks', $configData[$subModule])) {
                if (
                    $this->wire('page')->process == 'ProcessPageEdit'
                    && $this->editedPage
                    && !($this->editedPage->template->flags & \ProcessWire\Template::flagSystem)
                ) {
                    $selector = 'include=all, sort=' . $this->editedPage->parent->sortfield . ', parent=' . $this->editedPage->parent;
                    $prevnextlinks = array();
                    $siblings = $this->editedPage->siblings;

                    if (count($siblings) > 1) {

                        $next = $this->editedPage->next($selector);
                        $prev = $this->editedPage->prev($selector);

                        if (!$next->id) {
                            $next = $siblings->first;
                            $isFirst = true;
                        }

                        if (!$prev->id) {
                            $prev = $siblings->last;
                            $isLast = true;
                        }

                        $edit_next_text = isset($isFirst) ? ' ' . \ProcessWire\__('Edit first:', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module') : \ProcessWire\__('Edit next:', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
                        $edit_prev_text = isset($isLast) ? ' ' . \ProcessWire\__('Edit last:', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module') : \ProcessWire\__('Edit previous:', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');

                        if ($prev->editable()) {
                            $prevnextlinks['prev'] = array(
                                'title' => $edit_prev_text . ' ' . ($prev->title ? $prev->title : $prev->name),
                                'url'   => $prev->editUrl
                            );
                        }

                        if ($next->editable()) {
                            $prevnextlinks['next'] = array(
                                'title' => $edit_next_text . ' ' . ($next->title ? $next->title : $next->name),
                                'url'   => $next->editUrl
                            );
                        }

                        // add js chunk to be expanded as HTML
                        if (!empty($prevnextlinks)) {
                            $this->wire('config')->js("AOS_prevnextlinks", $prevnextlinks);
                        }
                    }
                }
            }

        }

        // langTabHotkeySwitcher
//            if (in_array('langTabHotkeySwitcher', $configData[ $subModule ])) {
//                $jsFiles[] = $root . '/LangTabHotkeySwitcher/LangTabHotkeySwitcher.js';
//            }

        // ModuleTweaks
        $subModule = 'ModuleTweaks';
        if (in_array($subModule, $enabledSubmodules)) {

            if (in_array('loadCollapsedModuleInfos', $configData[$subModule])) {
                // Load module info fields collapsed
                $this->addHookAfter('InputfieldMarkup::render', function ($event) {
//                $this->addHookBefore('Inputfield::render', function ($event) {
                    $field = $event->object;
                    if ($field->id === 'ModuleInfo') {
//                        $field->collapsed = \ProcessWire\Inputfield::collapsedYesAjax;
//                        $field->collapsed = \ProcessWire\Inputfield::collapsedNo;
                        $field->collapsed = \ProcessWire\Inputfield::collapsedYes;
//                        $field->addClass('InputfieldStateCollapsed');
                    }
                });
            }

            if (in_array('moduleBrowserTitle', $configData[$subModule])) {
                // set browser title to module name
                if ($this->page->process && $this->page->process == 'ProcessModule') {
                    $this->wire('processBrowserTitle', $this->input->get('name'));
                }
            }

            if (in_array('moduleModal', $configData[$subModule])) {
                // load longclick js
                if ($this->page->process && $this->page->process == 'ProcessModule') {
                    $this->modules->get('JqueryCore')->use('longclick');
                }
            }
        }

        $subModule = 'PageListIcons';
        if (in_array($subModule, $enabledSubmodules)) {
            // use addHookBefore to add icon early (otherwise skips first!)
            $this->addHookBefore("ProcessPageListRender::getPageLabel", $this, 'addPageListIcon');
            $this->addHookAfter("ProcessPageListRender::getPageLabel", $this, 'replacePageListIconUnderscores');
        }


        $subModule = 'PageListThumbs';
        if (in_array($subModule, $enabledSubmodules)) {
            $this->addHookAfter('ProcessPageListRender::getPageLabel', $this, 'addPageListThumb');
        }

        $subModule = 'FileFieldTweaks';
        if (in_array($subModule, $enabledSubmodules)) {
            if (in_array('downloadAssetButton', $configData[$subModule])) {
                $this->addHookAfter('InputfieldImage::renderButtons', $this, 'addDownloadAssetLink');
                $this->addHookAfter('InputfieldFile::renderItem', $this, 'addDownloadAssetLink');
            }
            if (in_array('moveAssetButtons', $configData[$subModule])) {
//                $this->addHookAfter('InputfieldImage::renderButtons', $this, 'addMoveAssetButtons');
                $this->addHookAfter('InputfieldFile::renderItem', $this, 'addMoveAssetButtons');
            }
            if (in_array('imgSelectTitle', $configData[$subModule])) {
                $this->addHookAfter('ProcessPageEditImageSelect::execute', function ($event) {
                    $event->return .= "<script>if($('ul#select_images').length && window.addImageSelectLabels) addImageSelectLabels($('ul#select_images'));</script>";
                });
            }
            if (in_array('noFilenameTruncate', $configData[$subModule])) {
                $this->addHookBefore("InputfieldFile::render", $this, "disableFilenameTruncate");
            }
        }

        // add translations
        $configData['loc'] = array(
            'add_new'                  => \ProcessWire\__('Add new', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'),
            'save'                     => \ProcessWire\__('Save', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'),
            'save_and_exit'            => \ProcessWire\__('Save + Exit', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'),
            'save_and_reload'          => \ProcessWire\__('Save + Reload', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'),
            'remove_all_fields'        => \ProcessWire\__('Remove All', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'),
            'apply_to_all'             => \ProcessWire\__('Apply to all', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'),
            'check_all'                => \ProcessWire\__('Check all', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'),
            'clear_all'                => \ProcessWire\__('Clear all', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'),
            'removing'                 => \ProcessWire\__('Removing...', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'),
            'cancel'                   => \ProcessWire\__('Cancel', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'),
            'delete_action'            => \ProcessWire\__('Delete', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'),
            'permanent_delete_confirm' => \ProcessWire\__('Delete permanently?', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'),
            'untitled'                 => \ProcessWire\__('Untitled', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module')
        );

        // add modified enabledSubmodules to JS config (modified by roles)
        // note: array_values is used to have values-only array in JS
        $configData['enabledSubmodules'] = array_values($enabledSubmodules);
        $configData['aosUrl'] = $this->config->urls->AdminOnSteroids;
//        $configData['aosModuleUrl']      = $this->config->urls->admin . 'module/edit?name=AdminOnSteroids';

        // do not add JS to page on login page
        if ($this->page->id != 23) {

            // custom CKEaddons config js and css

            $this->addAsset('CKEStyle', $configData);
            $this->addAsset('CKEScript', $configData);
            $this->addAsset('CKEtemplates', $configData);

            // add css and js files
            foreach ($cssFiles as $cssFile) {
                $styles->add($cssFile);
            }

            foreach ($jsFiles as $jsFile) {
                $scripts->add($jsFile);
            }

            // write module js config to page
            $this->wire('config')->js("AdminOnSteroids", json_encode($configData));
        }

        // add admin CSS/JS
        $this->addAsset('AdminStyle', $configData);
        $this->addAsset('AdminScript', $configData);
    }


    /**
     * Helper function for fields in a repeater
     */
//    public function getEditedPage($page)
//    {
//        if ($page instanceof \ProcessWire\RepeaterPage) {
//            return $this->getEditedPage($page->getForPage());
//        } else {
//            return $page;
//        }
//    }


    // uncheck "Active?" checkbox next to language names when adding a new page
    public function uncheckAddnewActive(\ProcessWire\HookEvent $event)
    {
        $page = $this->wire('page');

        // AOS is only available in the admin
//        if ($page->template != 'admin') {
//            return;
//        }

        if ($page->process == 'ProcessPageAdd' || ($page->process == 'ProcessPageEdit' && $this->wire('input')->get('new') == 1)) {
            $event->return = str_replace("checked='checked'", "", $event->return);
        }
    }


    public function addAsset($assetName, &$configData)
    {

        if (!isset($configData[$assetName])) {
            return false;
        }

        $asset = trim($configData[$assetName], '/ ');

        if (strlen($asset)) {

            // allow absolute or relative url
            $baseUrl = strpos($asset, 'http') !== false ? '' : $this->config->urls->httpRoot;

            if (strpos($assetName, 'CKE') !== false) {
                $configData['custom' . $assetName] = $baseUrl . $asset;
            } elseif ($assetName === 'AdminStyle') {
                $this->config->styles->add($baseUrl . $asset);
            } elseif ($assetName === 'AdminScript') {
                $this->config->scripts->add($baseUrl . $asset);
            }
        }
    }


    /**
     * Method to disable submodule (in Hooks).
     *
     * @param $submoduleName string
     * @param $configData    array
     *
     * @return array
     */
    public static function disableSubmodule($submoduleName, $configData)
    {

        $enabledSubmodules = $configData['enabledSubmodules'];
        $key = array_search($submoduleName, $enabledSubmodules);


        if ($key !== false) {
            unset($enabledSubmodules[$key]);
            $configData['enabledSubmodules'] = array_values($enabledSubmodules);
        }

        return $configData;
    }


    /**
     * Method to remove tweak from submodule (in Hooks).
     *
     * @param $tweakName     string
     * @param $submoduleName string
     * @param $configData    array
     *
     * @return array
     */
    public static function disableTweak($submoduleName, $tweakName, $configData)
    {

        if (isset($configData[$submoduleName])) {
            $submodule = $configData[$submoduleName];

            $key = array_search($tweakName, $submodule);

            if ($key !== false) {
                unset($submodule[$key]);
                $configData[$submoduleName] = array_values($submodule);
            }
        }

        return $configData;
    }


    public function addLanguageIndicators(\ProcessWire\HookEvent $event)
    {
        static $langs;

        $markup = $event->return;
        $p = $event->arguments("page");
        $page_languages = $p->getLanguages();
        $l = '';

        if ($langs === null) {
            $langs = \ProcessWire\wire('pages')->find('template=language,check_access=0');
        }

        //  show only if not all languages are active on the page
        if (count($page_languages) === 0 || count($langs) === count($page_languages)) {
            return false;
        }

        $page_language_ids = $page_languages->id();

        foreach ($langs as $lang) {
            $l .= '<b' . (in_array($lang->id, $page_language_ids) ? '  class="active"' : '') .' title="' . $lang->title . '">' . mb_substr($lang->title, 0, 3) . '</b>';
        }

        $event->return = $markup . '<i class="pagelist-langs">' . $l . '</i>';
    }


    public function addPageListIDs(\ProcessWire\HookEvent $event)
    {

        $markup = $event->return;
        $page = $event->arguments("page");

        // uncomment to disable in Tree menu
//        $options = $event->arguments('options');
//        if(!empty($options['noTags'])) return;

        // append an empty span with data-id after pagelist item text content
        if (strpos($markup, '<span') === false) {

            // check if there's a template icon
            // if found, save it to $icon, add the span, then prepend

            $icon = '';

            if (strpos($markup, '</i>') !== false) {
                $icon_with_markup = explode('</i>', $markup, 2);
                $icon = $icon_with_markup[0] . '</i>';
                $markup = $icon_with_markup[1];
            }

            $label_with_markup = explode('<', $markup, 2);

            $markup = $icon . trim($label_with_markup[0]) . '<span></span>' . (isset($label_with_markup[1]) ? ' <' . $label_with_markup[1] : '');
        }

        // check for label_title first and if not found, do a general str_replace.
        if (strpos($markup, 'label_title') !== false) {
            $markup = str_replace("<span class='label_title'",
                "<span class='label_title' data-pid='" . $page->id . "' ",
                $markup);

        } else {

            // limit the replacement to the first match
            $needle = '<span';
            $pos = strpos($markup, $needle);

            if ($pos !== false) {
                $markup = substr_replace($markup, "<span data-pid='" . $page->id . "' ", $pos, strlen($needle));
            }
        }

        $event->return = $markup;
    }


    /**
     * Disable filename truncation for InputfieldFile
     * https://github.com/processwire/processwire-requests/issues/83
     * https://github.com/rolandtoth/AdminOnSteroids/issues/39
     *
     * @param HookEvent $event
     */
    public function disableFilenameTruncate(\ProcessWire\HookEvent $event)
    {

        // do not process Image (and other) fields
        if ($event->object->class !== 'FieldtypeFile') {
            return;
        }

        // noShortName is used by InputfieldFile but not available as a config option
        $event->object->noShortName = 1;
    }


    public function addPageListMarkup(\ProcessWire\HookEvent $event)
    {

        $page = $event->arguments[0];
        $markup = $event->return;
        $submodule = 'PageListTweaks';
        $pageLabelField = $page->template->pageLabelField;

        if ($pageLabelField == "") {
            return false;
        }

        // using '//' in front temporarily disables the custom markup (return default "title")
        if (strpos($pageLabelField, '//') === 0) {
            $event->return = $page->title;

            return false;
        }

        $markupStartRegex = "/\[([A-Za-z]*)(\.)?([A-Za-z0-9-_\.]*)\]/";
        $markupCloseRegex = "/\[\/([A-Za-z]*?)\]/";
        $dateRegex = "/\(([0-9]*)\|date(:([a-zA-sZ:.\%_ \-\/]*))?\)*/";
        $emptyTagsRegex = "/(\[(.*)\])*/";

        if (isset(self::$configData[$submodule]) && in_array('pListMarkup', self::$configData[$submodule])) {

            // dates
            // format: (timestamp|date:Y-m-d)
            // (2313121|date:Y-m-d sd)
            // (2313121|date)
            // (|date:H:i:is)
            // (|date)

            $markup = preg_replace_callback($dateRegex, function ($match) {

                // set locale in config.php
                if (!$this->isLocaleSet) {
                    $configLocale = $this->wire('config')->getLocale;

                    if (is_object($configLocale) && ($configLocale instanceof Closure)) {
                        setlocale(LC_ALL, $configLocale());
                        $this->isLocaleSet = true;
                    }
                }

                $dateString = $match[1];
                $format = isset($match[2]) ? ltrim($match[2], ':') : '%Y-%m-%d';

                return empty($dateString) ? '&#216;' : strftime($format, $dateString);
            }, $markup);


            // starting tags with/without class
            $markup = preg_replace_callback($markupStartRegex, function ($match) {
                $class = (isset($match[2]) && isset($match[3]) && $match[2] == '.') ? ' class="' . $match[3] . '"' : '';

                // PW removes space and underscores
                $class = str_replace('.', ' ', $class);
                $class = str_replace('__', '-', $class);

                return '<' . $match[1] . $class . ' data-pitem>';
            }, $markup);

            // closing tags
            $markup = preg_replace($markupCloseRegex, '</$1>', $markup);

        } else {    // tweak is disabled, cleanup markup to avoid showing tokens

            // remove dates
            $markup = preg_replace($dateRegex, '', $markup);

            // remove markup tokens
            $markup = preg_replace($markupStartRegex, '', $markup);
            $markup = preg_replace($markupCloseRegex, '', $markup);
        }

        // also remove empty tags
        $markup = preg_replace("/<[A-Za-z]+><\/[A-Za-z]+>/", '', $markup);

        //$event->return = utf8_decode($markup);
        $event->return = $markup;
    }


    public function pageListMarkupGetLangValue(\ProcessWire\HookEvent $event)
    {

        $page = $event->arguments('page');
        $pageLabelField = trim($page->template->pageLabelField);

        if (empty($pageLabelField)) {
            return false;
        }

        // {title}[em.company]{company_ref.title}[/em] [em]{%date_created.label%}: ({date_created}|date:%Y. %B %d.)[/em] [em][i]{%portfolio_images.label%}: {portfolio_images.count}[/i][/em]

        $multilangFieldRegex = "/%([a-zA-Z0-9_]+)\.([a-zA-Z0-9_]+)%/";

        $pageLabelField = utf8_encode($pageLabelField);

        $pageLabelField = preg_replace_callback($multilangFieldRegex, function ($match) use ($page) {

            $field = $match[1];
            $property = $match[2];

            $langID = $this->wire('user')->language->isDefault() ? '' : $this->wire('user')->language->id;

            if (strlen($page->fields->$field->{$property . $langID}) == 0) {
                $langID = '';
            }

            return str_replace('.' . $property, '.' . $property . $langID, 'fieldgroup.' . trim($match[0], '%'));

            //}, utf8_encode($pageLabelField));
        }, $pageLabelField);

        $page->template->pageLabelField = utf8_decode($pageLabelField);
    }


    public function addNavItems(\ProcessWire\HookEvent $event)
    {
        $items = "";
        $NavItems_pages = isset(self::$configData['NavItems_pages']) ? self::$configData['NavItems_pages'] : false;
        $NavItems_pages_submenu = isset(self::$configData['NavItems_pages_submenu']) ? self::$configData['NavItems_pages_submenu'] : false;
        $NavItems_custom = isset(self::$configData['NavItems_custom']) ? self::$configData['NavItems_custom'] : false;
        $rootUrl = $this->wire('pages')->get(2)->url . 'page/?id=';

        // process pagelist select items
        if ($NavItems_pages) {

            $isFirst = true;
            $superuserFlag = false;

            foreach ($this->pages->getById($NavItems_pages) as $p) {

                $url = "javascript:";
                $editUrl = "";
                $activeClass = "";
                $inputId = $this->wire('input')->get->id;

                /**
                 * 7: Trash
                 * 21: Modules
                 * 304: Profile
                 */
                if ($p->id == 304) {

                    if ($this->wire('user')->hasPermission('profile-edit')) {
                        $url = $this->wire('pages')->get($p->id)->url;
                    } else {
                        continue;
                    }

                } else {
                    if ($p->id == 21) {

                        if ($this->wire('user')->isSuperUser()) {
                            $url = $this->config->urls->admin . 'module';
                        }

                    } else {
                        if ($p->id == 7) {

                            if ($p->listable()) {
                                $url = $this->config->urls->admin . 'page/?id=' . $p->id;
                                $editUrl = false;
                            } else {
                                continue;
                            }

                        } else {

                            if (!$p->listable()) {
                                continue;
                            }

                            $url = $rootUrl . $p->id;
                        }
                    }
                }

                if ($url == "") {
                    continue;

                } else {
                    $pageId = $p->id;

                    /**
                     * add active class only if:
                     * navItem id == GET id
                     * navItem id == current page id
                     * navItem id !== GET id and edited page is child page of the page
                     */

                    if (
                        $pageId == $inputId ||
                        $pageId == $this->page->id ||
                        (!in_array($inputId,
                                $NavItems_pages) && $pageId !== 1 && $this->editedPage && $this->editedPage->parent() && $pageId == $this->editedPage->parent()->id)
                    ) {
                        $activeClass = ' current';
                    }
                    $listUrl = '<a href="' . $url . '" class="page-list' . $activeClass . '">' . $p->title . '</a>';
                }

                $editUrl = ($editUrl === false) ? '' : $p->editable() ? '<a href="' . $p->editUrl() . '" class="page-edit"><i class="fa fa-pencil"></i></a>' : '';

                $firstClass = empty($items) ? ' first' : '';

                if ($isFirst && $NavItems_pages_submenu) {
                    $firstClass .= ' hasSubmenu';
                }

                $items .= '<li class="navItem' . $firstClass . '">';

                // start a submenu
                if ($isFirst && $NavItems_pages_submenu) {

                    // if title starts with "!" then only SuperUsers should see
                    if ($NavItems_pages_submenu[0] == '!') {
                        if (!$this->wire('user')->isSuperUser()) {
                            $superuserFlag = true;
                        }
                        // trim
                        $NavItems_pages_submenu = ltrim($NavItems_pages_submenu, '! ');
                    }

                    if (!$superuserFlag) {
                        $items .= '<a href="javascript:">' . $NavItems_pages_submenu . ' <i class="fa fa-caret-down"></i></a>';
                        $items .= '<ul>';
                        $items .= '<li>';
                    }

                    $isFirst = false;
                }

                if (!$superuserFlag) {
                    $items .= $listUrl . ' ' . $editUrl;
                    $items .= '</li>';
                }
            }

            // close the subenu
            if (!$superuserFlag && $NavItems_pages_submenu) {
                $items .= '</ul>';
            }

            $superuserFlag = false;
        }

        if ($NavItems_custom) {

            $settings = trim($NavItems_custom);
            $settings = explode("\n", $settings);
            $settings = array_filter($settings, 'trim');

            $rootUrl = rtrim($this->config->urls->admin, '/');
            $rootUrlHttp = $this->config->urls->httpAdmin;

            $superuserFlag = false;

            foreach ($settings as $pairs) {

                if (strpos($pairs, '//') === 0) {
                    continue;
                }

                // replace rootUrlHttp to avoid having ':' before explode
                $pairs = str_replace($rootUrlHttp, '', $pairs);

                // process submenus
                // start: --SubmenuName, end: --
                if (strpos($pairs, '--') === 0) {

                    if (strlen($pairs) > 2) {

                        $pairs = ltrim($pairs, '--');
                        $title = $pairs;
                        $url = '#';

                        // get submenu name and url if string contains ':'
                        if (strpos($pairs, ':') !== false) {
                            $setting = explode(':', $pairs);
                            $title = isset($setting[0]) ? trim($setting[0]) : $title;
                            $url = isset($setting[1]) ? trim($setting[1]) : $url;
                        }

                        // if title starts with "!" then only SuperUsers should see
                        if ($title[0] == '!') {
                            if (!$this->wire('user')->isSuperUser()) {
                                $superuserFlag = true;
                                continue;
                            }
                            // trim
                            $title = ltrim($title, '! ');
                        }

                        $items .= '<li class="navItem hasSubmenu">';
                        $items .= '<a href="' . $rootUrl . '/' . ltrim($url,
                                '/') . '">' . $title . ' <i class="fa fa-caret-down"></i></a>';
                        $items .= '<ul>';

                    } else {
                        // end tag
                        $items .= '</ul>';
                        $items .= '</li>';
                        $superuserFlag = false;
                    }
                    continue;
                }

                if (strpos($pairs, ':') === false) {
                    // perhaps it's a selector?
//                    $p = $this->wire('pages')->get(trim($pairs));
//                    if($p->id) {
//                        $pairs = $p->title . ':' . $this->wire('config')->urls->adminHttp . 'page/?id=' . $p->id;
//                    } else {
                    continue;
//                    }
                }

                if ($superuserFlag) {
                    continue;
                }

                $setting = explode(':', $pairs);

                $title = isset($setting[0]) ? trim($setting[0]) : null;
                $url = isset($setting[1]) ? trim($setting[1]) : null;

                if (is_null($title) || is_null($url)) {
                    continue;
                }

                // if title starts with "!" then only SuperUsers should see
                if ($title[0] == '!') {
                    if (!$this->wire('user')->isSuperUser()) {
                        continue;
                    }
                    // trim and add * to indicate it's admin only
                    $title = ltrim($title, '!') . "*";
                }

                $url = ltrim($url, '/');

                $activeClass = (strpos($_SERVER['REQUEST_URI'], $url) !== false) ? ' current' : '';

                $linkUrl = '<a href="' . $rootUrl . '/' . $url . '" class="page-list' . $activeClass . '">' . $title . '</a>';
                $items .= '<li class="navItem">' . $linkUrl . '</li>';
            }
        }

        if ($items == "") {
            return false;
        }

        $items = '<ul class="NavItems">' . $items . '</ul>';

//        $event->return = str_replace('</body>', $items . '</body>', $event->return);
        $event->return = str_replace('<body', '<body data-navitems="' . htmlspecialchars($items, ENT_QUOTES) . '"',
            $event->return);
    }


    /**
     * Add Delete button to pagelist
     */
    public function addDeleteButton(\ProcessWire\HookEvent $event)
    {

        $page = $event->arguments('page');

        // do not allow for pages having children
        if ($page->numChildren > 0) {
            return false;
        }

        if (!$page->trashable() || !$this->user->isSuperUser()) {
            return false;
        }

        $actions = array();
        $adminUrl = $this->wire('config')->urls->admin . 'page/';
        $icon = '';

//        $actions['delete_permanently'] = array(
        $actions['delete'] = array(
            'cn'   => 'Delete aos-pagelist-confirm',
            'name' => $icon . 'Delete',
            'url'  => $adminUrl . '?action=delete&id=' . $page->id,
            'ajax' => true
        );

        $event->return += $actions;
    }

    /**
     * Process action for addDeleteButton.
     *
     * @return bool
     */
    public function addDeleteButtonAction(\ProcessWire\HookEvent $event)
    {

        $page = $event->arguments(0);
        $action = $event->arguments(1);

        // do not allow for pages having children
        if ($page->numChildren > 0) {
            return false;
        }

        if ($action == 'delete') {

            //                            $page->setAndSave('title', $page->title . '-hello');
            $page->delete();

            $event->return = array(
                'action'          => $action,
                'success'         => true,
                'page'            => $page->id,
                'updateItem'      => $page->id,
                'message'         => 'Page deleted.',
                'remove'          => true,
                'refreshChildren' => false
            );
        }
    }

    /**
     * Add Trash button to pagelist (for non-SuperUsers)
     */
    public function addTrashButton($event)
    {
        $page = $event->arguments(0);
        $extras = $event->return;
        if ($page->trashable()) {
            $trash_icon = "<i class='fa fa-trash-o'></i>&nbsp;";
            $extras['trash'] = array(
                'cn'   => 'Trash aos-pagelist-confirm',
                'name' => $trash_icon . $this->_('Trash'),
                'url'  => $this->wire('config')->urls->admin . "page/?action=trash&id=$page->id",
                'ajax' => true
            );
        }
        $event->return = $extras;
    }


    public function addTemplateEditLinkPageList(\ProcessWire\HookEvent $event)
    {

        if (!isset(self::$configData['ListerTweaks_options'])) {
            return false;
        }

        // return if template edit action button is disabled for Lister
        if (in_array('hideTemplateEditAction', self::$configData['ListerTweaks_options']) &&
            ($this->page->process == 'ProcessPageLister' || $this->page->process == 'ProcessPageListerPro')
        ) {
            return false;
        }

        $page = $event->arguments("page");
        $actions = $event->return;
        $template = $page->template;

        $templateEditUrl = $this->config->urls->httpAdmin . 'setup/template/edit?id=' . $template->id;

        $editTemplateAction = array(
            'editTemplate' => array(
                // use "Edit" to enable built-in long-click feature
                'cn'   => 'Edit',
                'name' => $template->name,
                'url'  => $templateEditUrl
            )
        );

        // put the template edit action before the Extras (
        $key_extras = array_search('extras', array_keys($actions));

        // home, trash, etc doesn't have 'extras', add the button to the end
        if (!$key_extras) {
            $key_extras = count($actions);
        }

        $actions = array_merge(array_slice($actions, 0, $key_extras, true), $editTemplateAction,
            array_slice($actions, $key_extras, null, true));

        $event->return = $actions;
    }


    public function getFormattedOptionName($obj)
    {
        return !empty($obj->label) ? $obj->label . ' (' . $obj->name . ')' : $obj->name;
    }


    public function setupAdminColumnsTabs($fields, $form)
    {

        $dataColumnBreaks = array();

        foreach ($fields as $f) {

            // add data-attributes fo JS
            $notes = $f->notes;

            if (empty($notes)) {
                // try default notes (PW bug with overrides?)
                $notes = $this->fields->get($f->name)->notes;
            }

            if (!empty($notes)) {
                $notes = trim($notes);

                if (strpos($notes, 'colbreak_') !== 0) {
                    return;
                }

                $notes = str_replace('colbreak_', '', $notes);

                if (strpos($notes, ':') !== false) {
                    $notes = array_map('trim', explode(':', $notes));
                } else {
                    $notes = array($notes, 67);
                }
                $dataColumnBreaks[$f->name] = $notes;
            }
        }

        if (!empty($dataColumnBreaks)) {
            $form->wrapAttr('data-column-break', json_encode($dataColumnBreaks));
        }

    }


    public function addAdminClasses(\ProcessWire\HookEvent $event)
    {
        $theme = $event->object;
        $user = $this->wire('user');

        foreach ($user->roles as $role) {
            $theme->addBodyClass("role-{$role->name}");
        }

        if (!$this->wire('user')->isSuperuser()) {
            $theme->addBodyClass("role-nonsuperuser");
        }

        // add currently edited page info (template, id)
//        if ($this->editedPage) {
//            $theme->addBodyClass("template-" . $this->editedPage->template->name);
//            $theme->addBodyClass("id-" . $this->editedPage->id);
//        }
        $theme->addBodyClass("user-{$user->name}");
    }


    public function setupAdminColumns(\ProcessWire\HookEvent $event)
    {

        $form = $event->return;
        $fields = $form->children();
        $colBreakField = $fields->get('aos_column_break');
        $colWidths = array(67, 33);
        $tabOpenFields = $fields->find('hasFieldtype=FieldtypeFieldsetTabOpen');

        if ($tabOpenFields->count()) {
            $this->setupAdminColumnsTabs($tabOpenFields, $form);
        }

        if (!$colBreakField) {
            return false;
        }

        // stop if colBreakField is inside a tab
        $tabSeen = false;

        foreach ($fields as $field) {

            if ($field->hasFieldtype == 'FieldtypeFieldsetTabOpen') {
                $tabSeen = true;
            }

            if ($field->name == $colBreakField->name) {

                if ($tabSeen) {
                    // there was a TabOpen field first, remove colBreakField and stop
                    $form->remove($colBreakField);

                    return false;

                } else {
                    // colBreakField is not inside a tab
                    break;
                }
            }
        }

        if ($colBreakField->columnWidth) {
            $colWidths = array($colBreakField->columnWidth, 100 - $colBreakField->columnWidth);
        }

        $fsetLeft = $this->modules->get("InputfieldFieldset");
        $fsetLeft->attr('class', $fsetLeft->attr('class') . ' aos_col_left');
        $fsetLeft->wrapAttr('style', 'width: ' . $colWidths[0] . '%');
        $fsetLeft->wrapAttr('data-splitter-default', $colWidths[0]);

        $fsetRight = $this->modules->get("InputfieldFieldset");
        $fsetRight->attr('class', $fsetRight->attr('class') . ' aos_col_right');
        $fsetRight->wrapAttr('style', 'width: ' . $colWidths[1] . '%');
        $fsetRight->wrapAttr('data-splitter-default', $colWidths[1]);

        // add template name and user id for Split.js
        $fsetRight->wrapAttr('data-splitter-storagekey',
            'splitter_' . $this->editedPage->template->name . '_' . $this->wire('user')->id);


        $this->modules->get('FieldtypeFieldsetClose');
        if (class_exists('\ProcessWire\InputfieldFieldsetClose')) {
            $fsetLeftEnd = new \ProcessWire\InputfieldFieldsetClose;
            $fsetRightEnd = new \ProcessWire\InputfieldFieldsetClose;
        } else {
            $fsetLeftEnd = new \ProcessWire\InputfieldFieldsetClose;
            $fsetRightEnd = new \ProcessWire\InputfieldFieldsetClose;
        }

        $fsetLeftEnd->name = 'aos_col_left' . \ProcessWire\FieldtypeFieldsetOpen::fieldsetCloseIdentifier;
        $fsetRightEnd->name = 'aos_col_right' . \ProcessWire\FieldtypeFieldsetOpen::fieldsetCloseIdentifier;

        $fset = $fsetLeft;
        $rightItems = false;

        foreach ($fields as $f) {

            // stop on first Tab field
            if ($f->hasFieldtype == 'FieldtypeFieldsetTabOpen') {
                break;
            }

            // if colBreakField reached, remove it and start adding fields to the right column
            if (!$rightItems && $f == $colBreakField) {
                $form->remove($colBreakField);
                $fset = $fsetRight;
                $rightItems = true;
                continue;
            }

            $fset->add($form->get($f->name));
            $form->remove($form->get($f->name));
        }

        $form->add($fsetLeft);
        $form->add($fsetLeftEnd);

        $form->add($fsetRight);
        $form->add($fsetRightEnd);
    }


    /**
     * Override field settings per user/page/field poperties.
     *
     * @param HookEvent $event
     *
     * @return void
     */
    public function setFieldOverrides(\ProcessWire\HookEvent $event)
    {
        $field = $event->object;
        $user = $this->wire('user');
        $fields = $this->wire('fields');
        $is_multilang = is_object(\ProcessWire\wire('languages'));

        foreach ($this->FieldOverrides as $selector => $values) {

            // remove items with empty values
            array_filter($values, function ($v) {
                return $v !== "";
            });

            // check enabled state
            if (isset($values['?enabled'])) {
                if ($values['?enabled'] == 0) {
                    continue;
                }
                unset($values['?enabled']);
            }

            // check if user matches
            if (isset($values['?user'])) {
                // 1: try user role first
                // 2: try selector next
                $userrole = $values['?user'];
                unset($values['?user']);

                if (!($user->is("roles=" . $userrole) || ($this->isValidSelectorString($userrole) && $user->is($userrole)))) {
                    continue;
                }
            }

            // if "?field" key is present, check if current field matches
            if (isset($values['?field'])) {
                // 1: try field name first
                // 2: try a selector for the field

                $fieldname = $values['?field'];
                unset($values['?field']);

                if (!(($fields->get('name=' . $fieldname) && $field->name === $fieldname) || ($this->isValidSelectorString($fieldname) && in_array($field->id, array_values($fields->find($fieldname)->id()))))) {
                    continue;
                }
            }

            // check "?page" (id/selector for currently edited page)
            if (isset($values['?page'])) {
                $selector = $values['?page'];
                unset($values['?page']);

                if (is_numeric($selector)) {
                    $selector = "id=" . $selector;
                }

                if ($this->editedPage && !$this->editedPage->is($selector)) {
                    continue;
                }
            }

            foreach ($values as $key => $v) {

                // check for _lang_{languageName}
                if ($is_multilang) {
                    $lang_pos = strpos($key, '_lang_');
                    if ($lang_pos > 1) {
                        $language_name = mb_substr($key, $lang_pos + strlen('_lang_'));
                        $lang = $this->wire('languages')->get($language_name);
                        if ($lang->id) {
                            $key = mb_substr($key, 0, $lang_pos) . $lang->id;
                        } else {
                            continue;
                        }
                    }
                }

                switch ($key) {
                    case 'stop':
                        return; //do not process next ini group
                        break;
                    case 'toolbar_add':
                        $toolbar = $field->toolbar . ', ' . trim($v, ',');
                        $field->toolbar = $this->removeDuplicatesFromString($toolbar);
                        break;
                    case 'toolbar_remove':
                        $buttons = $this->removeDelimitedStringChunks($field->toolbar, $v);
                        $field->toolbar = $buttons;
                        break;
                    case 'formatTags':
                        $format_tags = str_replace(array(',', ' '), array(';', ''), $v);
                        $field->formatTags = $this->removeDuplicatesFromString($format_tags, ';');
                        break;
                    case 'formatTags_add':
                        $v = trim(str_replace(array(',', ' '), array(';', ''), $v), ';');
                        $format_tags = $field->formatTags . ';' . $v;
                        $field->formatTags = $this->removeDuplicatesFromString($format_tags, ';');
                        break;
                    case 'formatTags_remove':
                        $v = trim(str_replace(array(',', ' '), array(';', ''), $v), ';');
                        $format_tags = $this->removeDelimitedStringChunks($field->formatTags, $v, ';');
                        $field->formatTags = $format_tags;
                        break;
                    case 'id':
                    case 'name':
                    case 'type':
                    case 'inputfieldClass':
                        continue;
                        break;
                    default:
                        $field->{$key} = $v;
                }
            }

            continue;   // move to next ini group
        }
    }


    /**
     * Check if string looks like a ProcessWire selector.
     *
     * @param $str
     *
     * @return bool
     */
    public function isValidSelectorString($str)
    {
        $validSelectorOperators = \ProcessWire\Selectors::getOperatorChars();

        return count(array_intersect(str_split($str), $validSelectorOperators)) > 0;
    }


    /**
     * Remove duplicate strings from a separated string.
     *
     * @param $str
     * @param string $delimiter
     *
     * @return string
     */
    public function removeDuplicatesFromString($str, $delimiter = ',')
    {
        return implode($delimiter, array_keys(array_flip(explode($delimiter, $str))));
    }


    /**
     * Remove string chunks from string.
     *
     * @param string $str       delimiter-separated string
     * @param string $substr    delimiter-separated string
     * @param string $delimiter chunks separator
     *
     * @return string
     */

    public function removeDelimitedStringChunks($str, $substr, $delimiter = ',')
    {
        $chunks = explode($delimiter, $str);
        $chunks_to_remove = explode($delimiter, $substr);

        if (!is_array($chunks) || !is_array($chunks_to_remove)) {
            return $str;
        }

        $chunks = array_map('trim', $chunks); //trim whitespace
        $chunks_to_remove = array_map('trim', $chunks_to_remove); //trim whitespace

        $out = array_diff($chunks, $chunks_to_remove);

        return implode($delimiter, $out);
    }


    public function addDownloadAssetLink(\ProcessWire\HookEvent $event)
    {
        $markup = $event->return;
        $url = $event->arguments[0]->url;

        $downloadLink = '<a href="' . $url . '" target="_blank" class="aos_downloadAsset" download title="' . \ProcessWire\__('Download',
                \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module') . '"><i class="fa fa-download"></i></a>';

        if (strpos($markup, 'InputfieldImageEdit') !== false) {
            // for image fields
            $markup = str_replace('</h2>', $downloadLink . '</h2>', $markup);
        } else {
            // for file fields
            $markup = $downloadLink . $markup;
        }

        $event->return = $markup;
    }


    public function addMoveAssetButtons(\ProcessWire\HookEvent $event)
    {

        $markup = '<span class="aos_moveAssets">';
        $markup .= '<i title="' . \ProcessWire\__('Move to last', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module') . '" class="fa fa-step-backward" data-down></i>';
        $markup .= '<i title="' . \ProcessWire\__('Move to first', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module') . '" class="fa fa-step-forward" data-up></i>';
        $markup .= '</span>';

        $event->return = $markup . $event->return;
    }


    public function addAOSToggleLink(\ProcessWire\HookEvent $event)
    {

        $parts = $event->return;

        $div_class = ($this->adminTheme === 'AdminThemeUikit') ? 'pw-container uk-container uk-container-expand' : '';

        $enabledText = \ProcessWire\__('Disable', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module') . ' AdminOnSteroids';   // Disable AdminOnSteroids
        $disabledText = \ProcessWire\__('Enable', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module') . ' AdminOnSteroids';   // Enable AdminOnSteroids

        $linkStyle = 'style="opacity: 0.75; color: inherit !important; margin-left: 0; display: inline-block; padding: 4px 0; margin-right: 1px;"';
        $mouseover = 'onmouseover="this.style.textDecoration=\'underline\'" onmouseout="this.style.textDecoration=\'none\'"';

        $modulePage = $this->config->urls->admin . 'module/edit?name=AdminOnSteroids';
        $configLink = '<a href="' . $modulePage . '" ' . $linkStyle . ' title="' . \ProcessWire\__('Configure module',
                \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module') . '"><i class="fa fa-cog"></i></a>';

        $configLinkMarkup = '<div class="' . $div_class . '"><div class="uk-grid"><div class="uk-width-2-3@m uk-flex-first@m uk-text-center uk-text-left@m uk-first-column"><p style="margin-top: 10px; font-size: 
0.9rem;" class=""><a 
href="' . $modulePage . '&toggle=1" 
class="aos_toggle" 
' . $linkStyle . '><i 
class="fa fa-medkit"></i> 
<span ' . $mouseover . '>
' . ($this->enabled ? $enabledText : $disabledText) . '</span></a> ' . $configLink . '</p></div></div></div>';

        $parts['footer'] .= $configLinkMarkup;

        $event->return = $parts;
    }


    public function addTemplateEditLink(\ProcessWire\HookEvent $event)
    {
        if (!$this->editedPage || $this->editedPage->template == 'admin') {
            return;
        }

        $template = $this->editedPage->template;

        $target = isset(self::$configData['FieldAndTemplateEditLinks']) ? self::$configData['FieldAndTemplateEditLinks'] : '';

        $target = ($target === 'pw-panel') ? $target . ' pw-panel-reload' : $target;

        $templateEditUrl = $this->config->urls->admin . 'setup/template/edit?id=' . $template->id;
        $templateEditLink = '<a href="' . $templateEditUrl . '" class="aos_EditTemplate ' . $target . '" target="_blank">' . $template->name . '<i class="fa fa-pencil"></i></a>';


        if ($this->adminTheme === 'AdminThemeDefault') {
            $event->return = str_replace('<li class=\'title\'>', '<li class="title">' . $templateEditLink, $event->return);
        } else {
            // todo check for AdminThemeUikit
            $event->return = preg_replace('/<h1 id="title">(<span>)?(.*)(<\/span>)?<\/h1>/', '<h1 id="title"><span>${2}</span>' . $templateEditLink . '</h1>', $event->return, 1);
        }
    }


    public function addFieldEditLinks(\ProcessWire\HookEvent $event)
    {

        $inputfield = $event->object;

        if ($inputfield->type == 'hidden') {
            return;
        }

        if (strpos($event->return, 'data-editurl')) {
            return;
        }

        if ($field = $this->fields->get($inputfield->name)) {

            if (!is_object($field)) {
                return;
            }

            // add class to wrapper to be able to use :hover even if label is unavailable (eg. checkbox field)
            $inputfield->wrapAttr('class', $inputfield->wrapAttr('class') . ' aos_hasTooltip');


            $editFieldUrl = $this->config->urls->admin . 'setup/field/edit?id=' . $field->id;

            $editFieldTooltip = '<em class="aos_EditField">' . $inputfield->name . '<i class="fa fa-pencil"></i></em>';

            // needed to allow HTML in label
            $inputfield->entityEncodeLabel = false;
            $inputfield->label = '<span class="title">' . $editFieldTooltip . $inputfield->label . '</span>';

            // use hidden link to be able to use modal/panel
            // note: link is not added to the label tag because it won't be clickable

            $target = isset(self::$configData['FieldAndTemplateEditLinks']) ? self::$configData['FieldAndTemplateEditLinks'] : '';

            $target = ($target === 'pw-panel') ? $target . ' pw-panel-reload' : $target;

            // add tooltip if there's no label (checkbox)
            if ($inputfield instanceof \ProcessWire\InputfieldCheckbox) {
                $event->return = str_replace('</label>', $editFieldTooltip . '</label>', $event->return);
            }

            $link = '<a href="' . $editFieldUrl . '" class="' . $target . ' aos_EditFieldLink" data-field-name="' . $inputfield->name . '" target="_blank" style="display: none !important;">Edit</a>';

            $event->return = $link . $event->return;
        }
    }


    public function addTranslatorLinks(\ProcessWire\HookEvent $event)
    {
        $form = $event->return;
        $textdomain = $this->wire('input')->get('textdomain');
        $currentLangID = $this->wire('input')->get('language_id');
        $links = '';
        $adminUrl = $this->wire('urls')->admin;

        foreach ($this->wire('languages') as $lang) {
            $lang_id = $lang->id;
            if ($lang_id == $currentLangID) {
                continue;
            }
            $links .= '<li><a href="' . $adminUrl . 'setup/language-translator/edit/?textdomain=' . $textdomain . '&language_id=' . $lang_id . '">' . $lang->title . ' <span>' . $lang->name . '<span></a></li>';
        }

        $links = '<ul class="aos-language-translator-links">' . $links . '</ul>';
        $event->return = str_replace('</h2>', '</h2>' . $links, $form);
    }


    public function addPageListUnselectButtons(\ProcessWire\HookEvent $event)
    {
        $field = $event->object;

        $originalID = '';
        $originalTitle = ($field->value && $this->pages->get($field->value)) ? $this->pages->get($field->value)->title : '';

        if (isset($this->PageListTweaks) && in_array('pListIDs', $this->PageListTweaks) && $this->user->isSuperUser()) {
            $originalID = ($field->value && $this->pages->get($field->value)) ? $this->pages->get($field->value)->id : '';
        }

        $restoreTitleTag = strlen($originalTitle) ? 'title="' . \ProcessWire\__('Restore',
                \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module') . ' &quot;' . $originalTitle . '&quot;"' : '';

        $clearButton = '<button class="aos_pagelist_unselect clear ui-button ' . ($field->value ? '' : 'empty') . '" title="' . \ProcessWire\__('Clear',
                \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module') . '"><i class="fa fa-times-circle"></i></button>';

        $restoreButton = $field->value ? '<button class="aos_pagelist_unselect restore ui-button initial" ' . $restoreTitleTag . ' data-title-original="' . $originalTitle . '" data-pid="' . $originalID . '" data-value-original="' . $field->value . '" ><i class="fa fa-undo"></i></button>' : '';

        $event->return = $restoreButton . $clearButton . $event->return;
    }


    public function addIUCLink(\ProcessWire\HookEvent $event)
    {

        $inputfield = $event->object;
        $url = $inputfield->value ? $inputfield->value : '';

        // do not add to regular autocomplete field, only to edit link modal
        if ($inputfield instanceof \ProcessWire\InputfieldPageAutocomplete) {
            return false;
        }

        // if url is an array, it's a simple pageautocomplete field (not FieldtypeAssistedURL)
        // https://github.com/rolandtoth/AdminOnSteroids/issues/13
        if (is_array($url)) {
            return false;
        }

        $configData = self::$configData;
        $editedPage = $this->editedPage;
        $editLinkAttrsArray = array();
        $editLinkAttrs = '';

        if (!empty($configData['IUC_enabledTemplates']) && !in_array($editedPage->template->name,
                $configData['IUC_enabledTemplates'])
        ) {
            return false;
        }

        if (!empty($configData['IUC_enabledFields']) && !in_array($inputfield->name,
                $configData['IUC_enabledFields'])
        ) {
            return false;
        }


        // process locked fields
        if (in_array($inputfield->collapsed, array(7, 8))) {
            $target = isset($configData['IUC_target']) ? $configData['IUC_target'] : '';
            $target = ($target === 'pw-panel') ? $target . ' pw-panel-reload' : $target;
            $event->return = '<a href="' . $event->return . '" target="_blank" class="iuc iuc-locked-link ' . $target . '">' . $event->return . '</a>';

            return true;
        }


        if (isset($configData['IUC_mode'])) {

            $mode = implode(',', $configData['IUC_mode']);

            $editLinkAttrsArray['data-iuc-mode'][] = $mode;

            if (in_array('button', $configData['IUC_mode'])) {
                $buttonPosition = isset($configData['IUC_buttonPosition']) ? $configData['IUC_buttonPosition'] : '';
                $editLinkAttrsArray['class'][] = 'iuc iuc-button ' . $buttonPosition;
            } else {
                $editLinkAttrsArray['class'][] = 'iuc iuc-hidden';
            }
        }

        if (isset($configData['IUC_target'])) {

            // add wrap class for repeaters (only if mode is pw-panel)

            if ($configData['IUC_target'] === 'pw-panel' && strpos($inputfield->attr('id'), '_repeater') !== false) {
                $inputfield->wrapAttr('class', $inputfield->wrapAttr('class') . ' pw-panel-items');
            }

            $editLinkAttrsArray['class'][] = $configData['IUC_target'];

            if ($configData['IUC_target'] === 'pw-panel') {
                // disable load on hover
                $editLinkAttrsArray['class'][] = 'pw-panel-reload';
            }
        }

        if (isset($configData['IUC_forceHttp']) && $configData['IUC_forceHttp'] == 1) {
            $editLinkAttrsArray['data-iuc-force-http'][] = 1;
        }

        foreach ($editLinkAttrsArray as $attr_name => $values) {
            $editLinkAttrs .= $attr_name . '="' . implode(' ', $values) . '" ';
        }

        // add CSS class for easier selection
        $inputfield->addClass('iuc-input');

        $editLinkMarkup = '<a href="' . $url . '"' . $editLinkAttrs . ' target="_blank"><i class="fa fa-arrow-right"></i></a>';

        $event->return = $editLinkMarkup . $event->return;

        return false;
    }


// add template name to title
    public function addTemplateLinkPageList(\ProcessWire\HookEvent $event)
    {

        $page = $event->arguments('page');

        $template = $page->template;

        $target = isset(self::$configData['FieldAndTemplateEditLinks']) ? self::$configData['FieldAndTemplateEditLinks'] : '';

        $target = ($target === 'pw-panel') ? $target . ' pw-panel-reload' : $target;

        $templateEditUrl = $this->config->urls->admin . 'setup/template/edit?id=' . $template->id;
        $templateEditLink = '<a href="' . $templateEditUrl . '" class="aos_EditTemplate ' . $target . '" target="_blank">' . $template->name . '<i class="fa fa-pencil"></i></a>';

        $event->return = str_replace('</span>', $templateEditLink . '</span>', $event->return);
    }


    function replacePageListIconUnderscores(\ProcessWire\HookEvent $event)
    {
        $event->return = str_replace('___', ' ', $event->return);
    }


    function addPageListIcon(\ProcessWire\HookEvent $event)
    {

        $page = $event->arguments[0];
        $template = $page->template;

        // intentional "="
        if (!($settings = $this->getTextareaPairs('PageListIcons'))) {
            return false;
        }

        if (!is_array($settings)) {
            return false;
        }

        foreach ($settings as $pairs) {

            if (strpos($pairs, '//') === 0) {
                continue;
            }

            $setting = explode(':', $pairs);

            $customIcon = isset($setting[0]) ? trim($setting[0]) : null;
            $selector = isset($setting[1]) ? trim($setting[1]) : null;

            // save original icon to session
            $sessionIconName = 'icon_orig_' . $template->id;
            $currentIcon = $template->getIcon();

            if (strpos($currentIcon, 'icon_orig_') === 0) {
                $this->wire('session')->set($sessionIconName, $currentIcon);
            }

            // if only a string is supplied without "=" in it, consider it as a template
            // eg. cirle-o: basic-page matches other items too - use template=basic-page (maybe because common fieldgroup?)
            if (is_string($selector) && strpos($selector, '=') === 0) {
                $selector = "template=" . $selector;
            }

            if ($page->is($selector) || $page->matches($selector)) {
                $template->setIcon($customIcon);
            }
        }
    }


    public function addPageListThumb(\ProcessWire\HookEvent $event)
    {
        // disable in Tree menu (wide items may go blank because the ellipsis added by PW)
        // bug: causes thumbs not loaded if tree was initially collapsed
//        if ($this->wire('config')->ajax) return false;
        // this works fine:
        $options = $event->arguments('options');
        if (!empty($options['noTags'])) {
            return;
        }


        $page = $event->arguments('page');
        $field = null;

        // intentional "="
//        if (!($settings = $this->getTextareaPairs('PageListThumbs_options', 'PageListThumbs_items'))) return false;

        if (!($settings = $this->getTextareaPairs('PageListThumbs_items'))) {
            return false;
        }

        if (!is_array($settings)) {
            return false;
        }

        foreach ($settings as $pairs) {

            if (strpos($pairs, '//') === 0) {
                continue;
            }

            $setting = explode(':', $pairs);

            $f = isset($setting[0]) ? trim($setting[0]) : null;
            $selector = isset($setting[1]) ? trim($setting[1]) : null;

            if (is_null($f) || !$page->$f || (!$page->$f instanceof \ProcessWire\Pageimage && !$page->$f instanceof \ProcessWire\Pageimages) || count($page->$f) == 0) {
                continue;
            }

            if (is_null($selector)) {
                // break if there's no selector (any page will match)
                $field = $f;
                break;

            } elseif ($page->is($selector)) {
                // break if page matches
                $field = $f;
                break;
            }
        }


        if (is_null($field)) {
            return false;
        }

        $field = ($page->$field instanceof \ProcessWire\Pageimages) ? $page->$field->first() : $page->$field;

        $classes = array('addlink');

        // always use 48px to avoid generation too much thumbs, resize with CSS
        $thumbSize = 48;

        if (isset($this->PageListThumbs_style) && !empty($this->PageListThumbs_style)) {
            $classes[] = $this->PageListThumbs_style;
        }

        if (in_array('square', $classes)) {
//                $thumbSrc = $field->size($thumbSize, $thumbSize, array('cropping' => false))->url;
            $thumbSrc = $field->size($thumbSize, $thumbSize, array('cropping' => true, 'upscaling' => true))->url;
//                $thumbSrc = $field->size($thumbSize, $thumbSize, array('cropping' => true, 'forceNew' => true))->url;
        } else {
            $thumbSrc = $field->height($thumbSize)->url;
        }

        $PageListThumbs_options = isset($this->PageListThumbs_options) ? $this->PageListThumbs_options : null;

        $img = '<img src="' . $thumbSrc . '" />';

        if (!is_null($PageListThumbs_options)) {

            if (in_array('alignright', $PageListThumbs_options)) {
                $classes[] = 'alignright';
            }

            $img = '<a href="' . rtrim($this->config->urls->httpRoot,
                    '/') . $page->editUrl() . '" class="aos_pageListLink">' . $img . '</a>';
        }

        if (!empty($classes)) {
            $classes = implode(' ', $classes);
        }

        $event->return = '<figure class="' . $classes . '">' . $img . '</figure>' . $event->return;
    }


    public function getTextareaPairs($propertyName)
    {

        if ($this->{$propertyName}) {
            return $this->{$propertyName};
        }

        $data = isset($this->data[$propertyName]) ? $this->data[$propertyName] : null;

        if (is_null($data)) {
            return false;
        }

        // build settings array
        $settings = trim($data);
        $settings = explode("\n", $settings);
//        $settings = array_filter($settings, 'trim');
        $settings = array_map('trim', $settings); //trim whitespace
        $settings = array_filter($settings, 'trim');  // remove empty lines

        $this->{$propertyName} = $settings;

        return $settings;
    }

    public function addAdminLangSwitcher(\ProcessWire\HookEvent $event)
    {

        if ($this->wire('languages') && $this->wire('pages')->find('template=language, check_access=0')->count() > 1) {

            $parts = $event->return;

            $lang_items = '';
            $userLangId = $this->user->language->id;

            foreach ($this->languages as $lang) {
                $activeClass = $lang->id == $userLangId ? ' class="active"' : '';
                $lang_items .= '<li' . $activeClass . '><a href="' . $_SERVER['REQUEST_URI'] . '" data-lang-id="' . $lang->id . '"><span class="lang-title">' . $lang->title . '</span> <span class="lang-name">' . $lang->name . '</span></a></li>';
            }

            $parts['masthead'] .= '<li class="aos_adminLangSwitcher" style="display: none;"><a href="#">' . $this->user->language->title . '</a><ul>' . $lang_items . '</ul></li>';

            $event->return = $parts;
        }
    }


    public function addRoleFields($submoduleName, $data, $parent)
    {
        $f = \ProcessWire\wire('modules')->get("InputfieldAsmSelect");
        $f->attr('name', $submoduleName . 'Roles');
        $f->label = \ProcessWire\__($submoduleName . ' roles', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->skipLabel = \ProcessWire\Inputfield::skipLabelHeader;
        $f->attr('data-asm-placeholder', \ProcessWire\__('ROLES', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->showIf = 'enabledSubmodules=' . $submoduleName;
        $f->setAsmSelectOption('sortable', false);
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;

        $f->addOptions($this->allRoles);

        if (isset($data[$f->name])) {
            $f->attr('value', $data[$f->name]);
        }

        $parent->add($f);
    }


    public function getModuleConfigInputfields(array $data)
    {

        $defaultData = self::getDefaultData();
        $data = array_merge(self::getDefaultData(), $data);

        // remove  "Force showing system templates" tweak if it's unchecked when saving AOS
        $this->wire('modules')->addHookBefore('saveModuleConfigData', function () use ($data) {
            if (in_array('showSystemTemplates', $data['Misc'])) {
                $this->wire('session')->remove('ProcessTemplateFilterSystem');
            }
        });

        // exception to ListerTweaks: use "[DEFAULTS]" if empty
//        if (empty($data['ListerTweaks_find'])) {
//            $data['ListerTweaks_find'] = array('[DEFAULTS]');
//        }
//        if (empty($data['ListerTweaks_users'])) {
//            $data['ListerTweaks_users'] = array('[DEFAULTS]');
//        }

        $wrapper = new \ProcessWire\InputfieldWrapper();

        // Enable module ----------------------------------------------- //

        $f = \ProcessWire\wire('modules')->get('InputfieldCheckbox');
        $f->name = 'enabled';
        $f->label = \ProcessWire\__('Enable module', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;
        $f->attr('value', $data[$f->name]);

        $f->checked = ($f->value == 1) ? 'checked' : '';

        $wrapper->add($f);


        // Submodules ----------------------------------------------- //


        $f = \ProcessWire\wire('modules')->get("InputfieldCheckboxes");
        $f->attr('name', 'enabledSubmodules');
        $f->label = \ProcessWire\__('Submodules', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;

        $intro = \ProcessWire\__('Click on the boxes to enable or disable submodules. Use the "cog" icon to jump to their configuration section.', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $markupText = \ProcessWire\__('More info', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');

        $f->prependMarkup = <<< HTML
     <p>$intro $markupText: <a href="https://github.com/rolandtoth/AdminOnSteroids/wiki" target="_blank">AdminOnSteroids @ GitHub</a>
</p>
HTML;

        $f->addOption('AddNewChildFirst',
            '**AddNewChildFirst**' . \ProcessWire\__('Add new page as first child instead of last', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('AdminTweaks', '**AdminTweaks**' . \ProcessWire\__('Default admin theme tweaks', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('AsmTweaks', '**AsmTweaks**' . \ProcessWire\__('asmSelect tweaks', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('CKEaddons', '**CKEaddons**' . \ProcessWire\__('Autoload CKEditor plugins and skins', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('DeselectRadios', '**DeselectRadios**' . \ProcessWire\__('Enable clearing checked radio buttons', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('FieldAndTemplateEditLinks',
            '**FieldAndTemplateEditLinks**' . \ProcessWire\__('Shortcuts to templates and fields&nbsp;(SuperUser only)', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('FieldOverrides', '**FieldOverrides**' . \ProcessWire\__('Conditionally override field settings', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('FileFieldTweaks', '**FileFieldTweaks**' . \ProcessWire\__('File and image field enhancements', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('FocusInputOnLangTabSwitch',
            '**FocusInputOnLangTabSwitch**' . \ProcessWire\__('Focus input on switching language tabs', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('Hotkeys', '**Hotkeys**' . \ProcessWire\__('Hotkey tweaks', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('InputfieldURLChecker',
            '**InputfieldURLChecker**' . \ProcessWire\__('Add button or hotkey to check URL', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('LongClickDuration', '**LongClickDuration**' . \ProcessWire\__('Custom long-click action duration', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('ListerTweaks', '**ListerTweaks**' . \ProcessWire\__('Lister enhancements', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('Misc', '**Misc**' . \ProcessWire\__('Miscellaneous tweaks', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('ModuleTweaks', '**ModuleTweaks**' . \ProcessWire\__('Module related tweaks (SuperUser only)', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('NavItems', '**NavItems**' . \ProcessWire\__('Add pages to navigation', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('PageListIcons', '**PageListIcons**' . \ProcessWire\__('Add pagelist icons', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('PageListThumbs', '**PageListThumbs**' . \ProcessWire\__('Add pagelist thumbnails', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('PageListTweaks', '**PageListTweaks**' . \ProcessWire\__('Pagelist related tweaks', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('PagePreviewBtn', '**PagePreviewBtn**' . \ProcessWire\__('Add preview link next to page title', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('RenoTweaks', '**RenoTweaks**' . \ProcessWire\__('Reno admin theme tweaks', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('RestrictTreeDropdown', '**RestrictTreeDropdown**' . \ProcessWire\__('Hide tree dropdown by role', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('Tooltips', '**Tooltips**' . \ProcessWire\__('Move field descriptions and notes to tooltips', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('UikitTweaks', '**UikitTweaks**' . \ProcessWire\__('Uikit admin theme tweaks', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));

        $f->attr('value', isset($data[$f->name]) ? $data[$f->name] : $defaultData[$f->name]);

        $wrapper->add($f);


        // Tweaks Fieldset ----------------------------------------------- //

        $fset = \ProcessWire\wire('modules')->get("InputfieldFieldset");
        $fset->attr('name', 'tweaks');
        $fset->label = \ProcessWire\__('Submodule options', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $fset->collapsed = \ProcessWire\Inputfield::collapsedNever;

        // AddNewChildFirst ----------------------------------------------- //

        $fsetANCF = \ProcessWire\wire('modules')->get("InputfieldFieldset");
        $fsetANCF->attr('name', 'AddNewChildFirst');
        $fsetANCF->label = \ProcessWire\__('AddNewChildFirst', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $fsetANCF->showIf = 'enabledSubmodules=AddNewChildFirst';

        // Enabled templates
        $f = \ProcessWire\wire('modules')->get('InputfieldAsmSelect');
        $f->name = 'AddNewChildFirst_enabledTemplates';
        $f->label = \ProcessWire\__('Enabled templates', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->attr('data-asm-placeholder', \ProcessWire\__('Add templates...', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;

        $f->addOption('__all__', '[ALL]');

        foreach ($this->wire('templates') as $t) {
            if ($t->name == 'home' || ($t->flags & \ProcessWire\Template::flagSystem)) {
                continue;
            }
            $f->addOption($t->name, self::getFormattedOptionName($t));
        }

        if ($data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }

        $fsetANCF->add($f);

        $fset->add($fsetANCF);

        // AdminTweaks ----------------------------------------------- //

        $f = \ProcessWire\wire('modules')->get("InputfieldCheckboxes");
        $f->attr('name', 'AdminTweaks');
        $f->label = \ProcessWire\__('AdminTweaks', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->showIf = 'enabledSubmodules=AdminTweaks';
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;

        $f->addOption('headSticky', \ProcessWire\__('Sticky header', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('wide', \ProcessWire\__('Set wider main content', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('leftTopnav', \ProcessWire\__('Align top menu to the left', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));

        if ($data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }

        $fset->add($f);


        // AsmTweaks ----------------------------------------------- //

        $f = \ProcessWire\wire('modules')->get("InputfieldCheckboxes");
        $f->attr('name', 'AsmTweaks');
        $f->showIf = 'enabledSubmodules=AsmTweaks';
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;

        $f->addOption('asmCollapse', \ProcessWire\__('Collapse fieldset/tab items on double click', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('asmLeftX', \ProcessWire\__('Move delete button to the left', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('fieldMiddleEdit', \ProcessWire\__('Edit field in new tab on middle click (no template context)', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('editFieldWidth',
            \ProcessWire\__('Template editor: add clickable field width percentages and display divisions on width slider',
                \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));

        if ($data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }

        $fset->add($f);


        // CKEaddons ----------------------------------------------- //

        $fsetCKE = \ProcessWire\wire('modules')->get("InputfieldFieldset");
        $fsetCKE->attr('name', 'CKEaddons');
        $fsetCKE->label = \ProcessWire\__('CKEaddons', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $fsetCKE->showIf = 'enabledSubmodules=CKEaddons';
//        $fsetCKE->collapsed = \ProcessWire\Inputfield::collapsedNever;

        // Plugins
        $f = \ProcessWire\wire('modules')->get('InputfieldAsmSelect');
        $f->name = 'CKEaddons_plugins';
        $f->label = \ProcessWire\__('Plugins', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->description = \ProcessWire\__('Plugins marked with asterisk add toolbar items.', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');

        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;

        $addsToolbarButtonText = '*';

        $f->addOption('autogrow', 'Auto Grow');
        $f->addOption('autolink', 'Auto Link');
        $f->addOption('autosave', 'Auto Save');
        $f->addOption('codemirror', 'CodeMirror');
        $f->addOption('codesnippet', 'Code Snippet');
        $f->addOption('templates', 'Content Templates');
        $f->addOption('div', 'Div' . $addsToolbarButtonText);
        $f->addOption('find', 'Find' . $addsToolbarButtonText);
        $f->addOption('indentblock', 'Indent Block' . $addsToolbarButtonText);
        $f->addOption('justify', 'Justify' . $addsToolbarButtonText);
        $f->addOption('textselection', 'Keep TextSelection');
        $f->addOption('keystrokes', 'Keystrokes');
        $f->addOption('magicline', 'Magic Line');
        $f->addOption('maximize', 'Maximize' . $addsToolbarButtonText);
        $f->addOption('oembed', 'Media (oEmbed)' . $addsToolbarButtonText);
        $f->addOption('showblocks', 'Show Blocks' . $addsToolbarButtonText);
        $f->addOption('token', 'Token' . $addsToolbarButtonText);

        if (isset($data[$f->name]) && $data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }

        $fsetCKE->add($f);

        // Enabled fields
        $cke_fields = $this->fields->find('inputfieldClass=InputfieldCKEditor');

        $f = \ProcessWire\wire('modules')->get('InputfieldAsmSelect');
        $f->name = 'CKEaddons_enabledFields';
        $f->label = \ProcessWire\__('Enabled fields&nbsp;(for plugins only)', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
//        $f->description = \ProcessWire\__('Note: selected fields will restrict plugins only and not the skin.', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->attr('data-asm-placeholder', \ProcessWire\__('Add fields...', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;
        $f->columnWidth = 66;

        foreach ($cke_fields as $cke_field) {
            $f->addOption($cke_field->name, self::getFormattedOptionName($cke_field));
        }

        if ($data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }

        $fsetCKE->add($f);

        // Skin
        $f = \ProcessWire\wire('modules')->get('InputfieldRadios');
        $f->name = 'CKEaddons_skin';
        $f->label = \ProcessWire\__('CKEditor skin', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;
        $f->optionColumns = 3;

        $f->addOption('default', 'default');
        $f->addOption('lightwire', 'LightWire');

        if ($data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }

        $fsetCKE->add($f);

        $fset->add($fsetCKE);


        // ListerTweaks ----------------------------------------------- //

        // system labels + id, path
        $extraFieldNames = array(
            'id',
            'name',
            'path',
            'status',
            'template',
            'templates_id',
            'modified',
            'created',
            'published',
            'modified_users_id',
            'created_users_id',
            'parent',
            'num_children',
        );

        $fsetLT = \ProcessWire\wire('modules')->get("InputfieldFieldset");
        $fsetLT->attr('name', 'ListerTweaks');
        $fsetLT->label = \ProcessWire\__('ListerTweaks', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $fsetLT->showIf = 'enabledSubmodules=ListerTweaks';

        // Find lister

        $f = \ProcessWire\wire('modules')->get('InputfieldAsmSelect');
        $f->name = 'ListerTweaks_find';
        $f->label = \ProcessWire\__('Find lister columns', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;

        $lister_fieldnames = $this->wire('fields')->find('type!=FieldtypeFieldsetOpen|FieldtypeFieldsetClose|FieldtypeFieldsetTabOpen|FieldtypeFieldsetTabClose, sort=label')->name();
        $lister_fieldnames = array_merge($lister_fieldnames, $extraFieldNames);
        natcasesort($lister_fieldnames);

        array_unshift($lister_fieldnames, '[DEFAULTS]');

        foreach ($lister_fieldnames as $fieldname) {
            $f->addOption($fieldname);
        }


        $f->attr('value', (isset($data[$f->name]) && $data[$f->name]) ? $data[$f->name] : '');

        $fsetLT->add($f);

        $fset->add($fsetLT);

        // User lister

        $f = \ProcessWire\wire('modules')->get('InputfieldAsmSelect');
        $f->name = 'ListerTweaks_users';
        $f->label = \ProcessWire\__('Users lister columns', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;

        $lister_fieldnames = $this->wire('templates')->get('user')->fields->find('name!=pass, sort=label')->name();
        $lister_fieldnames = array_merge($lister_fieldnames, $extraFieldNames);
        natcasesort($lister_fieldnames);

        array_unshift($lister_fieldnames, '[DEFAULTS]');

        foreach ($lister_fieldnames as $fieldname) {
            $f->addOption($fieldname);
        }

        $f->attr('value', (isset($data[$f->name]) && $data[$f->name]) ? $data[$f->name] : '');

        $fsetLT->add($f);

        // hoverActions

        $f = \ProcessWire\wire('modules')->get("InputfieldCheckboxes");
        $f->attr('name', 'ListerTweaks_options');
        $f->label = \ProcessWire\__('Lister options', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;

        $f->addOption('listerHoverBtn', \ProcessWire\__('Show action buttons on hover', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('hideTemplateEditAction', \ProcessWire\__('Hide template edit action', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));

        $f->attr('value', isset($data[$f->name]) ? $data[$f->name] : $defaultData[$f->name]);

        $fsetLT->add($f);


        $fset->add($fsetLT);

        // DeselectRadios ----------------------------------------------- //

        $f = \ProcessWire\wire('modules')->get("InputfieldCheckboxes");
        $f->attr('name', 'DeselectRadios');
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;
        $f->description = \ProcessWire\__('', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->notes = \ProcessWire\__('', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->showIf = 'enabledSubmodules=DeselectRadios';

        $f->addOption('allowRequired', \ProcessWire\__('Enable for required fields&nbsp;(not recommended)', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));

        $f->attr('value', isset($data[$f->name]) ? $data[$f->name] : $defaultData[$f->name]);

        $fset->add($f);

        // FieldAndTemplateEditLinks ----------------------------------------------- //

        $f = \ProcessWire\wire('modules')->get("InputfieldRadios");
        $f->attr('name', 'FieldAndTemplateEditLinks');
        $f->showIf = 'enabledSubmodules=FieldAndTemplateEditLinks';
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;
        $f->optionColumns = 3;

        $f->addOption('pw-blank', \ProcessWire\__('Open in new tab', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('pw-panel', \ProcessWire\__('Open in panel', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('pw-modal', \ProcessWire\__('Open in modal', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));

        if ($data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }

        $fset->add($f);

        // FileFieldTweaks ----------------------------------------------- //

        $f = \ProcessWire\wire('modules')->get("InputfieldCheckboxes");
        $f->attr('name', 'FileFieldTweaks');
        $f->showIf = 'enabledSubmodules=FileFieldTweaks';
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;
        $f->description = \ProcessWire\__('', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->notes = \ProcessWire\__('', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');

        $f->addOption('filterbox', \ProcessWire\__('Filter box', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('downloadAssetButton', \ProcessWire\__('Add asset download button', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('imgSelectTitle', \ProcessWire\__('Add image titles to image select dialog', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('moveAssetButtons', \ProcessWire\__('Add move to first/last buttons', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('noFilenameTruncate', \ProcessWire\__('Disable filename truncation for File fields', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));

        if ($data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }

        $fset->add($f);


        // FieldOverrides ----------------------------------------------- //

        if ($this->wire('modules')->isInstalled('InputfieldAceExtended')) {
            $f = $this->wire('modules')->get('InputfieldAceExtended');
            $f->mode = 'ini';
            $f->modes = array('ini');
            $f->theme = 'twilight';
        } else {
            $f = $this->wire('modules')->get('InputfieldTextarea');
        }

        $f->rows = 8;
        $f->attr('name', 'FieldOverrides');
        $f->label = \ProcessWire\__('FieldOverrides', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->showIf = 'enabledSubmodules=FieldOverrides';
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;

        if (isset($this->FieldOverridesFile) && !empty($this->FieldOverridesFile)) {
            $f->notes = \ProcessWire\__('Additional items are prepended from this file (Asset Paths):', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module') . ' `' . $this->FieldOverridesFile . '`';
        }

        if ($data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }

        $fset->add($f);


        // FocusInputOnLangTabSwitch ----------------------------------------------- //

        $f = \ProcessWire\wire('modules')->get("InputfieldRadios");
        $f->attr('name', 'FocusInputOnLangTabSwitch');
        $f->showIf = 'enabledSubmodules=FocusInputOnLangTabSwitch';
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;
        $f->description = \ProcessWire\__('', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->notes = \ProcessWire\__('', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');

        $f->addOption('focus', \ProcessWire\__('Focus', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('moveEnd', \ProcessWire\__('Move cursor to the end', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('selectAll', \ProcessWire\__('Select all', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('nothing', \ProcessWire\__('Do nothing', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->optionColumns = 4;

        if ($data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }

        $fset->add($f);

        $f = \ProcessWire\wire('modules')->get("InputfieldRadios");
        $f->attr('name', 'FocusInputOnLangTabSwitchCKE');
        $f->label = \ProcessWire\__('FocusInputOnLangTabSwitch CKE', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->showIf = 'enabledSubmodules=FocusInputOnLangTabSwitch';
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;
        $f->description = \ProcessWire\__('', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->notes = \ProcessWire\__('', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');

        $f->addOption('focus', \ProcessWire\__('Focus', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('moveEnd', \ProcessWire\__('Move cursor to the end', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('selectAll', \ProcessWire\__('Select all', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('nothing', \ProcessWire\__('Do nothing', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->optionColumns = 4;

        if ($data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }

        $fset->add($f);

        // Hotkeys ----------------------------------------------- //

        $f = \ProcessWire\wire('modules')->get("InputfieldCheckboxes");
        $f->attr('name', 'Hotkeys');
        $f->showIf = 'enabledSubmodules=Hotkeys';
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;

        $f->addOption('breadcrumbTweaks', \ProcessWire\__('Add long-click and ctrl+click actions to breadcrumbs', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('removeNoticeHotkey', \ProcessWire\__('Remove notices on first ESC keypress', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('save', \ProcessWire\__('Save on', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module') . ' `ctrl+s`');
        $f->addOption('focusSearch', \ProcessWire\__('Focus search on', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module') . ' `alt+d`');
        $f->addOption('addPageTreeTrigger', \ProcessWire\__('Open page tree panel on', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module') . ' `alt+o`');
        $f->addOption('filterboxHotkey', \ProcessWire\__('Focus filterbox on', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module') . ' `als+s`');

        if ($data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }

        $fset->add($f);

        // InputfieldURLChecker ----------------------------------------------- //

        $fsetIUC = \ProcessWire\wire('modules')->get("InputfieldFieldset");
        $fsetIUC->attr('name', 'InputfieldURLChecker');
        $fsetIUC->label = \ProcessWire\__('InputfieldURLChecker', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $fsetIUC->showIf = 'enabledSubmodules=InputfieldURLChecker';
//        $fsetIUC->collapsed = \ProcessWire\Inputfield::collapsedNever;

        // Mode
        $f = \ProcessWire\wire('modules')->get('InputfieldCheckboxes');
        $f->name = 'IUC_mode';
        $f->label = \ProcessWire\__('Mode', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->columnWidth = 50;
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;
        $f->addOption('button', \ProcessWire\__('Button', 'IUC'));
        $f->addOption('ctrl-shift-click', \ProcessWire\__('Ctrl + Shift + Click', 'IUC'));
        $f->addOption('ctrl-shift-enter', \ProcessWire\__('Ctrl + Shift + Enter', 'IUC'));

        if ($data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }

        $fsetIUC->add($f);

        // Mode - button
        $f = \ProcessWire\wire('modules')->get('InputfieldRadios');
        $f->name = 'IUC_buttonPosition';
        $f->label = \ProcessWire\__('Button position', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;
        $f->columnWidth = 50;
        $f->addOption('button-left', \ProcessWire\__('Left side of the field', 'IUC'));
        $f->addOption('button-right', \ProcessWire\__('Right side of the field', 'IUC'));
        $f->showIf = 'IUC_mode=button';
        $f->requiredIf = 'IUC_mode=button';

        if ($data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }

        $fsetIUC->add($f);

        // Target
        $f = \ProcessWire\wire('modules')->get('InputfieldRadios');
        $f->name = 'IUC_target';
        $f->label = \ProcessWire\__('Open URL in...', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
//        $f->notes     = \ProcessWire\__('Iframe mode fails if the target website does not allow iframe embed.', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;
        $f->addOption('pw-blank', \ProcessWire\__('new tab', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('pw-modal', \ProcessWire\__('modal', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
//        $f->addOption('pw-panel', \ProcessWire\__('panel', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->optionColumns = 3;

//        $f->attr('value', isset($data[ $f->name ]) ? $data[ $f->name ] : $dataIUC[ $f->name ]);

        if ($data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }

        $fsetIUC->add($f);

        $f = \ProcessWire\wire('modules')->get('InputfieldCheckbox');
        $f->name = 'IUC_forceHttp';
        $f->label = \ProcessWire\__('Force HTTP prefix', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;

        $f->attr('value', $data[$f->name]);

        $f->checked = ($f->value == 1) ? 'checked' : '';

        $fsetIUC->add($f);

        // Enabled templates
        $f = \ProcessWire\wire('modules')->get('InputfieldAsmSelect');
        $f->name = 'IUC_enabledTemplates';
        $f->label = \ProcessWire\__('Enabled templates', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->attr('data-asm-placeholder', \ProcessWire\__('Add templates...', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;
        $f->columnWidth = 50;

        foreach ($this->wire('templates') as $t) {
            $f->addOption($t->name, self::getFormattedOptionName($t));
        }

        if ($data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }

        $fsetIUC->add($f);


        // Enabled fields asmSelect
        $url_fields = \ProcessWire\wire('fields')->find('type=FieldtypeURL');

        // add asm select only if there is any URL type field

        if (count($url_fields) > 0) {

            $f = \ProcessWire\wire('modules')->get('InputfieldAsmSelect');
            $f->name = 'IUC_enabledFields';
            $f->label = \ProcessWire\__('Enabled fields', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
            $f->collapsed = \ProcessWire\Inputfield::collapsedNever;
            $f->columnWidth = 50;

            foreach ($url_fields as $url_field) {
                $f->addOption($url_field->name, self::getFormattedOptionName($url_field));
            }

            $f->attr('data-asm-placeholder', \ProcessWire\__('Add fields...', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));

//            $f->attr('value', isset($data[ $f->name ]) ? $data[ $f->name ] : $dataIUC[ $f->name ]);
            if ($data[$f->name]) {
                $f->attr('value', $data[$f->name]);
            }

        } else {

            // add info that no URL type fields are available
            $f = \ProcessWire\wire('modules')->get('InputfieldMarkup');
            $f->name = 'no_url_fields';
            $f->label = \ProcessWire\__('Enabled fields', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
            // doesn't work
            // $f->collapsed = \ProcessWire\Inputfield::collapsedNever;
            $f->markupText = \ProcessWire\__('There is no URL field available', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        }

        $fsetIUC->add($f);

        $fset->add($fsetIUC);

        // LongClickDuration ----------------------------------------------- //

        $f = \ProcessWire\wire('modules')->get("InputfieldText");
        $f->attr('name', 'LongClickDuration');
        $f->description = \ProcessWire\__('', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->notes = \ProcessWire\__('', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->showIf = 'enabledSubmodules=LongClickDuration';
        $f->attr('style', 'width: 100px; display: none !important;');
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;

        $f->attr('value',
            (isset($data[$f->name]) && (int)$data[$f->name] >= $defaultData[$f->name]) ? $data[$f->name] : $defaultData[$f->name]);

        $fset->add($f);

        // Misc ----------------------------------------------- //

        $f = \ProcessWire\wire('modules')->get("InputfieldCheckboxes");
        $f->attr('name', 'Misc');
        $f->showIf = 'enabledSubmodules=Misc';
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;

        $f->addOption('adminColumns', \ProcessWire\__('Add `aos_column_break` field to create admin columns', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('adminLangSwitcher', \ProcessWire\__('Add language switcher to the admin', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('addTranslatorLinks',
            \ProcessWire\__('Add links to Language Translator to edit current textdomain file in other languages', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('autosizeTextareas', \ProcessWire\__('Autosize textareas according to content', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('addOrRemoveFieldsTweaks',
            \ProcessWire\__('Add helper buttons to batch field add/remove confirmation pages&nbsp;("Clear all", "Apply to all")',
                \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('centerLogin', \ProcessWire\__('Center login form', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('homeOpenNewTab', \ProcessWire\__('Open Home/View site in new tab (topnav)', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('dataTableFilter', \ProcessWire\__('Add filter box to AdminDataTables', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('transFilter', \ProcessWire\__('Add filter box to Language Translator', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('langTabHotkeySwitcher', \ProcessWire\__('Switch language tabs on ctrl+arrow keys', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('noAnim', \ProcessWire\__('Disable all admin animations', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('hoverDropdown', \ProcessWire\__('Show save dropdown on hover instead on click', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('titleCaseToggle', \ProcessWire\__('Add toggle button to change case of Page title field', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('tabIndex', \ProcessWire\__('Add sequential tabindex to fields', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('emptyTrashTop', \ProcessWire\__('Move empty trash confirmation checkbox above trash items', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('showSystemTemplates', \ProcessWire\__('Force showing system templates', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('iconsFilter', \ProcessWire\__('Add filter box to template icon picker', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('uncheckAddnewActive',
            \ProcessWire\__('Add new page: uncheck `Active?` for non-default language names', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('hideAddNewDropdown',
            \ProcessWire\__('Hide the `Add new` dropdown button from above the main pagelist', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('stickyCKE', \ProcessWire\__('Sticky CKEditor toolbar', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('themeConfigLinks', \ProcessWire\__('Add Profile page links to configure admin themes (SuperUser only)', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('prevNextLinks', \ProcessWire\__('Add links to edit previous and next pages', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));


        if ($data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }

        $fset->add($f);

        // ModuleTweaks ----------------------------------------------- //

        $f = \ProcessWire\wire('modules')->get("InputfieldCheckboxes");
        $f->attr('name', 'ModuleTweaks');
        $f->showIf = 'enabledSubmodules=ModuleTweaks';
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;
        $f->description = \ProcessWire\__('', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->notes = \ProcessWire\__('', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');

        $f->addOption('moduleCompact', \ProcessWire\__('Compact module list', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('flatModules', \ProcessWire\__('Do not distribute modules into tabs', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('loadCollapsedModuleInfos', \ProcessWire\__('Load module info fields collapsed', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('moduleModal', \ProcessWire\__('Edit modules in modal on long-click', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('moduleFilter', \ProcessWire\__('Add filter box to module list', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('moduleBrowserTitle', \ProcessWire\__('Set browser title to module name', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));

        if ($data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }

        $fset->add($f);

        // NavItems ----------------------------------------------- //

        $fsetCNI = \ProcessWire\wire('modules')->get("InputfieldFieldset");
        $fsetCNI->attr('name', 'NavItems');
        $fsetCNI->label = \ProcessWire\__('NavItems', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $fsetCNI->showIf = 'enabledSubmodules=NavItems';


        $f = \ProcessWire\wire('modules')->get("InputfieldText");
        $f->attr('name', 'NavItems_pages_submenu');
        $f->label = \ProcessWire\__('Group selected pages into submenu:', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->attr('placeholder', \ProcessWire\__('submenu name... (optional)', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;

        if ($data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }

        $fsetCNI->add($f);

        $f = \ProcessWire\wire('modules')->get('InputfieldPageListSelectMultiple');
        $f->name = 'NavItems_pages';
        $f->label = \ProcessWire\__('Select pages', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;

        if ($data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }

        $fsetCNI->add($f);


        $f = \ProcessWire\wire('modules')->get("InputfieldTextarea");
        $f->attr('name', 'NavItems_custom');
        $f->label = \ProcessWire\__('Custom items', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->attr('placeholder', '// ! AdminOnSteroids: /module/edit?name=AdminOnSteroids');
        $f->rows = 3;
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;

        if ($data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }

        $fsetCNI->add($f);


        $fset->add($fsetCNI);

        // PageListIcons ----------------------------------------------- //

        $f = \ProcessWire\wire('modules')->get("InputfieldTextarea");
        $f->attr('name', 'PageListIcons');
        $f->label = \ProcessWire\__('PageList icons', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->showIf = 'enabledSubmodules=PageListIcons';

        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;

        if (isset($data[$f->name]) && $data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }

        $fset->add($f);

        // PageListThumbs ----------------------------------------------- //

        $fsetPageListThumbs = \ProcessWire\wire('modules')->get("InputfieldFieldset");
        $fsetPageListThumbs->attr('name', 'PageListThumbs');
        $fsetPageListThumbs->label = \ProcessWire\__('PageListThumbs', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $fsetPageListThumbs->showIf = 'enabledSubmodules=PageListThumbs';
//        $fsetPageListThumbs->collapsed = \ProcessWire\Inputfield::collapsedNever;

        $f = \ProcessWire\wire('modules')->get("InputfieldRadios");
        $f->attr('name', 'PageListThumbs_style');
        $f->label = \ProcessWire\__('Style', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;

        $f->addOption('circle', \ProcessWire\__('circle', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('square', \ProcessWire\__('square', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('default', \ProcessWire\__('default', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->optionColumns = 4;

        if (isset($data[$f->name])) {
            $f->attr('value', $data[$f->name]);
        } else {
            $f->attr('value', $data['PageListThumbs'][$f->name]);
        }

        $fsetPageListThumbs->add($f);


        $f = \ProcessWire\wire('modules')->get("InputfieldTextarea");
        $f->attr('name', 'PageListThumbs_items');
        $f->label = \ProcessWire\__('Source', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->attr('placeholder', \ProcessWire\__('Enter field or field:selector pair(s)', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->rows = 3;
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;

        if (isset($data[$f->name])) {
            $f->attr('value', $data[$f->name]);
        } else {
            $f->attr('value', $data['PageListThumbs'][$f->name]);
        }

        $fsetPageListThumbs->add($f);


        $f = \ProcessWire\wire('modules')->get("InputfieldCheckboxes");
        $f->attr('name', 'PageListThumbs_options');
        $f->label = \ProcessWire\__('Settings', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'); // Thumb settings
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;

        $f->addOption('alignright', \ProcessWire\__('Align thumbs to right', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));

        if (isset($data[$f->name])) {
            $f->attr('value', $data[$f->name]);
        } else {
            $f->attr('value', $data['PageListThumbs'][$f->name]);
        }

        $fsetPageListThumbs->add($f);

        $fset->add($fsetPageListThumbs);

        // PageListTweaks ----------------------------------------------- //

        $f = \ProcessWire\wire('modules')->get("InputfieldCheckboxes");
        $f->attr('name', 'PageListTweaks');
        $f->label = \ProcessWire\__('PageListTweaks', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->showIf = 'enabledSubmodules=PageListTweaks';
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;

        $f->addOption('highlightRows', \ProcessWire\__('Highlight rows on hover', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('pListIDs', \ProcessWire\__('Show page IDs (SuperUser only)', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('refreshBtn', \ProcessWire\__('Add Refresh button to refresh page details displayed', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('deleteBtn', \ProcessWire\__('Add Delete button to delete page permanently (SuperUser only)', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('pListUnselect', \ProcessWire\__('Add unselect/restore buttons to PageListSelect', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('pListIconOnly', \ProcessWire\__('Icon-only pagelist actions', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('pListMiddleClick', \ProcessWire\__('Use middle mouse click/ctrl+click to View/Edit page', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('pListActiveBold', \ProcessWire\__('Make active pagelist items bold', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('pListShowActions', \ProcessWire\__('Always show pagelist actions', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('pListShowExtras', \ProcessWire\__('Always show extra actions', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('pListMarkup', \ProcessWire\__('Allow markup tokens for "List of fields to display"', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('pListCounters', \ProcessWire\__('Add counters to pagelist items', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('pListFullRowHover', \ProcessWire\__('Show pagelist actions on full row hover', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('pListTrash', \ProcessWire\__('Add Trash action also for non-SuperUsers', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
//        $f->addOption('pListLangs', \ProcessWire\__('Add language indicators', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));

        if (isset($data[$f->name]) && $data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }

        $fset->add($f);


        // PagePreviewBtn ----------------------------------------------- //

        $f = \ProcessWire\wire('modules')->get("InputfieldRadios");
        $f->attr('name', 'PagePreviewBtn');
        $f->label = \ProcessWire\__('PagePreviewButton', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->showIf = 'enabledSubmodules=PagePreviewBtn';
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;

        $f->addOption('pw-blank', \ProcessWire\__('Preview in new tab', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('pw-panel', \ProcessWire\__('Preview in panel', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('pw-modal', \ProcessWire\__('Preview in modal', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->optionColumns = 3;

        if ($data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }

        $fset->add($f);


        // RenoTweaks ----------------------------------------------- //

        $f = \ProcessWire\wire('modules')->get("InputfieldCheckboxes");
        $f->attr('name', 'RenoTweaks');
        $f->label = \ProcessWire\__('RenoTweaks', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->showIf = 'enabledSubmodules=RenoTweaks';
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;

        $f->addOption('headSticky', \ProcessWire\__('Sticky header', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('headStickyCompact', \ProcessWire\__('Compact header', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('miniScrollSb', \ProcessWire\__('Use mini scrollbar for sidebar', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('miniScrollMain', \ProcessWire\__('Use mini scrollbar for main content', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('sbSticky', \ProcessWire\__('Sticky sidebar', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('sbItemsVisible', \ProcessWire\__('Always show sidebar items (disable accordion)', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('sbSingleClickHeads', \ProcessWire\__('Single click navigation of sidebar headers', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('sbItemsInline', \ProcessWire\__('Inline sidebar items', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('sbQuickLinksHide', \ProcessWire\__('Hide sidebar quick links (flash icons)', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('sbAutoHide', \ProcessWire\__('Autohide sidebar', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('pListCompact', \ProcessWire\__('Use narrow pagelist rows', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('openSearch', \ProcessWire\__('Always show search field', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('headBtnToTitle', \ProcessWire\__('Place header button next to the main title', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('hoverTopSubmenus', \ProcessWire\__('Show topnav submenus on hover instead click', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('noticeLeftX', \ProcessWire\__('Move notice close buttons to the left', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));

        if ($data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }

        $fset->add($f);


        // RestrictTreeDropdown ----------------------------------------------- //

        $f = \ProcessWire\wire('modules')->get("InputfieldAsmSelect");
        $f->attr('name', 'RestrictTreeDropdown');
        $f->label = \ProcessWire\__('RestrictTreeDropdown', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->description = \ProcessWire\__('Hide tree dropdown for the following roles:', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->showIf = 'enabledSubmodules=RestrictTreeDropdown';
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;

        $roles = $this->wire('roles')->find("name!=guest");
        $f->addOption('all-roles', $this->_('all'));
        $f->addOption('nonsuperuser', $this->_('all non-superuser'));
        foreach ($roles as $select_option) {
            $f->addOption($select_option->name);
        }

        if ($data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }

        $fset->add($f);

        // Tooltips ----------------------------------------------- //

        $f = \ProcessWire\wire('modules')->get("InputfieldCheckboxes");
        $f->attr('name', 'Tooltips');
        $f->label = \ProcessWire\__('Tooltips', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->showIf = 'enabledSubmodules=Tooltips';
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;
        $f->description = \ProcessWire\__('', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->notes = \ProcessWire\__('', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');

//        $f->addOption('superuseronly', \ProcessWire\__('Only for SuperUsers', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('tooltipDesc', \ProcessWire\__('Enable for field descriptions', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('tooltipNotes', \ProcessWire\__('Enable for field notes', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('tooltipOverlay', \ProcessWire\__('Use overlay style', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));

        if ($data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }

        $fset->add($f);


        // UikitTweaks ----------------------------------------------- //

        $f = \ProcessWire\wire('modules')->get("InputfieldCheckboxes");
        $f->attr('name', 'UikitTweaks');
        $f->label = \ProcessWire\__('UikitTweaks', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->showIf = 'enabledSubmodules=UikitTweaks';
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;

        $f->addOption('headSticky', \ProcessWire\__('Sticky header', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));
        $f->addOption('headCompact', \ProcessWire\__('Compact (smaller) header', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module'));

        if ($data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }

        $fset->add($f);


        $wrapper->add($fset);


        // Assets paths

        $fsetPaths = \ProcessWire\wire('modules')->get("InputfieldFieldset");
        $fsetPaths->attr('name', 'AssetPaths');
        $fsetPaths->label = \ProcessWire\__('Asset Paths', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');

        $f = \ProcessWire\wire('modules')->get('InputfieldText');
        $f->name = 'AdminStyle';
        $f->label = \ProcessWire\__('Admin CSS', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->description = \ProcessWire\__('URL to a CSS file to be loaded in the admin, eg.',
                \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module') . ' "/site/templates/admin/admin.css"';
//        $f->columnWidth = 50;
        $f->collapsed = \ProcessWire\Inputfield::collapsedBlank;

        if ($data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }

        $fsetPaths->add($f);

        $f = \ProcessWire\wire('modules')->get('InputfieldText');
        $f->name = 'AdminScript';
        $f->label = \ProcessWire\__('Admin JavaScript', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->description = \ProcessWire\__('URL to a JavaScript file to be loaded in the admin, eg.',
                \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module') . ' "/site/templates/admin/admin.js"';
//        $f->columnWidth = 50;
        $f->collapsed = \ProcessWire\Inputfield::collapsedBlank;

        if ($data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }

        $fsetPaths->add($f);

        $f = \ProcessWire\wire('modules')->get('InputfieldText');
        $f->name = 'CKEStyle';
        $f->label = \ProcessWire\__('CKEditor custom CSS', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->description = \ProcessWire\__('URL to a CSS file to be loaded for CKEditors, eg.',
                \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module') . ' "/site/templates/admin/cke.css"';
//        $f->columnWidth = 50;
        $f->collapsed = \ProcessWire\Inputfield::collapsedBlank;

        if ($data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }
        $fsetPaths->add($f);

        $f = \ProcessWire\wire('modules')->get('InputfieldText');
        $f->name = 'CKEScript';
        $f->label = \ProcessWire\__('CKEditor custom configuration script', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->description = \ProcessWire\__('URL to a JavaScript file to be loaded for CKEditors, eg.',
                \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module') . ' "/site/templates/admin/cke.js"';
//        $f->columnWidth = 50;
        $f->collapsed = \ProcessWire\Inputfield::collapsedBlank;

        if ($data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }
        $fsetPaths->add($f);

        $f = \ProcessWire\wire('modules')->get('InputfieldText');
        $f->name = 'CKEtemplates';
        $f->label = \ProcessWire\__('CKEditor templates directory', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->description = \ProcessWire\__('URL to Content Templates CKEditor plugin templates directory, eg',
                \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module') . ' "/site/templates/admin/cke-templates.js"';
        $f->collapsed = \ProcessWire\Inputfield::collapsedBlank;

        if ($data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }
        $fsetPaths->add($f);

        $f = \ProcessWire\wire('modules')->get('InputfieldText');
        $f->name = 'FieldOverridesFile';
        $f->label = \ProcessWire\__('FieldOverrides file', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->description = \ProcessWire\__('File to prepend to the admin textarea config, eg',
                \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module') . ' "/site/templates/field-overrides.ini"';
        $f->collapsed = \ProcessWire\Inputfield::collapsedBlank;

        if ($data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }
        $fsetPaths->add($f);

        $f = \ProcessWire\wire('modules')->get('InputfieldText');
        $f->name = 'BrandingLogo';
        $f->label = \ProcessWire\__('Branding logo', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->description = \ProcessWire\__('Path to image for replacing ProcessWire logo in the header, eg.',
                \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module') . ' "/site/templates/images/brand-logo.svg"';
        $f->collapsed = \ProcessWire\Inputfield::collapsedBlank;

        if ($data[$f->name]) {
            $f->attr('value', $data[$f->name]);
        }
        $fsetPaths->add($f);

        $wrapper->add($fsetPaths);


        // Restore settings checkbox

        $f = \ProcessWire\wire('modules')->get('InputfieldCheckbox');
        $f->name = 'restore';
        $f->label = \ProcessWire\__('Restore settings on next install', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
//        $f->description = \ProcessWire\__('Enable saving module configuration data to file on uninstall to import it on next install.', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->notes = \ProcessWire\__('Enable saving module configuration data to file on uninstall to import it on next install.',
                \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module') . ' ' . \ProcessWire\__('Make sure to save the module first when changing this value.', \ProcessWire\wire("config")->paths->root . 'site/modules/AdminOnSteroids/AdminOnSteroids.module');
        $f->collapsed = \ProcessWire\Inputfield::collapsedNever;
        $f->value = $data[$f->name];

        $f->checked = ($f->value == 1) ? 'checked' : '';

        $wrapper->add($f);


        // add roles asmSelects

        // no need to add if module is disabled
        if ($this->enabled) {
            foreach ($data['enabledSubmodules'] as $submodule) {
                if (in_array($submodule, array('FieldAndTemplateEditLinks', 'ModuleTweaks', 'RestrictTreeDropdown'))) {
                    continue;
                }
                $this->addRoleFields($submodule, $data, $wrapper);
            }
        }

        return $wrapper;
    }
}
